### ISSUE TITLE
VStream plante dans la recherche de "ranma"

### ISSUE THREAD

**Issue by sviet2k** [Kodi-vStream/venom-xbmc-addons#2145]
**Décrivez le bug**
VStream crash dans la recherche de "ranma". C'est a cause du special caractere dans le titre: Ranma ½

**Votre system**
 - OS: Android
-  Appareil Android Rockchip box
 - Version Kodi 16
- Version Vstream

**Nous devons le reproduire**
La recherche de "Ranma" dans TV/Anime va planter VStream

**Comment by Arias800** [comment]
Aucun crash sous Kodi 18 après kodi 17 je sais pas  ^^

**Comment by TmpName** [comment]
Pareil chez moi ^^, kodi 17, ca cherche sans prb puis bug au moment de l'affichage
```
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 46: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\BRIX\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 272, in <module>
                                                main()
                                              File "C:\Users\BRIX\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 25, in __init__
                                                self.parseUrl()
                                              File "C:\Users\BRIX\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 94, in parseUrl
                                                searchGlobal()
                                              File "C:\Users\BRIX\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 247, in searchGlobal
                                                oGui.addFolder(result['guiElement'],result['params'])
                                              File "C:\Users\BRIX\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\gui\gui.py", line 287, in addFolder
                                                oListItem = self.createListItem(oGuiElement)
                                              File "C:\Users\BRIX\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\gui\gui.py", line 344, in createListItem
                                                oListItem.setArt({'poster': oGuiElement.getPoster(), 'thumb': oGuiElement.getThumbnail(), 'icon': oGuiElement.getIcon(),'fanart': oGuiElement.getFanart() })
                                              File "C:\Users\BRIX\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\gui\guiElement.py", line 407, in getIcon
                                                return os.path.join(unicode(self.__sRootArt, 'utf-8'), self.__sIcon)
                                              File "C:\Applications\Kodi\system\python\Lib\ntpath.py", line 85, in join
                                                result_path = result_path + p_path
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 46: ordinal not in range(128)
```

**Comment by Arias800** [comment]
Donc ça confirme le faite que sur Kodi 18 il ont du améliorer la prise en charge des caractères spéciaux

**Comment by TmpName** [comment]
Pas sur, ca ne fait le bug que sur le site voirfilms ws, il y a un caractere a la con dans l'url d'une l'image 
ranma-12-–-la-grande-bataille-de-chine.jpg

Je corrige ca de suite.

**Comment by LordVenom** [comment]
@sviet2k C'est réparer merci, tu ne verras pas la modif avant la prochaine mise a jour.Patience.

**Comment by sviet2k** [comment]
Merci LordVenom
