### ISSUE TITLE
Wawacity, aucun chargement apres selection du film/serie et plateformes de stream.

### ISSUE THREAD

**Issue by f3n3k** [Kodi-vStream/venom-xbmc-addons#2454]
**Décrivez le bug**
Impossible de stream les liens venant de wawacity. Chaque fois que je choisis un film/serie, je choisi la plateforme de stream (uptobox, openload etc) mais impossible d'aller plus loin, rien ne se charge apres la sélection du streameur.
En exemple je prends le film "Bibou", on arrive ensuite sur la page des sélections des plateformes de stream pour lire le film, je choisi pour exemple openload, je valide la ligne bibou 720p openload, mais rien ne se passe. Cela que pour les liens de wawacity, aucun soucis sur les autres sources.

Merci d'avance

Cordialement

**Votre system**
 - OS: Android
-  Appareil: Mibox 4k
 - Version Kodi  18
- Version Vstream 7.0

**Nous devons le reproduire**
Pour cela il nous faut:
- Wawacity
- chaque liens de films ou series.
- Tous

**Log**
https://slexy.org/view/s2jckiW7zP

**Image**
*****

**Plus**
*****

**Comment by f3n3k** [comment]
voici l'erreur dans le log:


2019-02-28 23:19:35.906 T:9507 WARNING: CPythonInvoker(19, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2019-02-28 23:19:42.559 T:9513  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
2019-02-28 23:19:42.722 T:9513  NOTICE: 	[PLUGIN] Vstream: load site wawacity and call function showMovies
2019-02-28 23:19:43.618 T:9513  NOTICE: 	[PLUGIN] Vstream: create dialog
2019-02-28 23:19:43.998 T:9513  NOTICE: 	[PLUGIN] Vstream: close dialog
2019-02-28 23:19:44.075 T:9513  NOTICE: 	[PLUGIN] Vstream: Table initialized
2019-02-28 23:19:44.168 T:9513 WARNING: CPythonInvoker(20, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2019-02-28 23:19:47.480 T:9522  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
2019-02-28 23:19:47.635 T:9522  NOTICE: 	[PLUGIN] Vstream: load site wawacity and call function showMoviesLinks
2019-02-28 23:19:48.556 T:9522  NOTICE: 	[PLUGIN] Vstream: create dialog
2019-02-28 23:19:48.710 T:9522  NOTICE: 	[PLUGIN] Vstream: close dialog
2019-02-28 23:19:48.745 T:9522  NOTICE: 	[PLUGIN] Vstream: Table initialized
2019-02-28 23:19:48.805 T:9522 WARNING: CPythonInvoker(21, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2019-02-28 23:19:51.047 T:9528  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
2019-02-28 23:19:51.212 T:9528  NOTICE: 	[PLUGIN] Vstream: load site wawacity and call function showHosters
2019-02-28 23:19:51.840 T:9528  NOTICE: 	[PLUGIN] Vstream: create dialog
2019-02-28 23:19:52.182 T:9528  NOTICE: 	[PLUGIN] Vstream: close dialog
2019-02-28 23:19:52.215 T:9528  NOTICE: 	[PLUGIN] Vstream: Table initialized
2019-02-28 23:19:52.281 T:9528 WARNING: CPythonInvoker(22, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2019-02-28 23:19:55.355 T:9533  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
2019-02-28 23:19:55.519 T:9533  NOTICE: 	[PLUGIN] Vstream: load site wawacity and call function Display_protected_link
2019-02-28 23:19:56.066 T:9533  NOTICE: 	[PLUGIN] Vstream: could not load site: wawacity error: list index out of range
2019-02-28 23:19:56.066 T:9533   ERROR: Traceback (most recent call last):
2019-02-28 23:19:56.066 T:9533   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 139, in parseUrl
2019-02-28 23:19:56.068 T:9533   ERROR:     function()
2019-02-28 23:19:56.068 T:9533   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/sites/wawacity.py", line 780, in Display_protected_link
2019-02-28 23:19:56.070 T:9533   ERROR:     sHtmlContent = DecryptddlProtect(sUrl)
2019-02-28 23:19:56.071 T:9533   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/sites/wawacity.py", line 844, in DecryptddlProtect
2019-02-28 23:19:56.072 T:9533   ERROR:     if host in s[0]:
2019-02-28 23:19:56.072 T:9533   ERROR: IndexError: list index out of range
2019-02-28 23:19:56.101 T:9533  NOTICE: 	[PLUGIN] Vstream: Table initialized
2019-02-28 23:19:56.170 T:9533 WARNING: CPythonInvoker(23, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2019-02-28 23:19:56.184 T:9532   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=Display_protected_link&sCat=1&sMovieTitle=Solis&sThumb=https%3a%2f%2fwawacity.ec%2f%2fimg%2ffilms%2ff4f34e27fe34232433bbfb6fc24edfc1.jpg&site=wawacity&siteUrl=https%3a%2f%2fwlnk.ec%2f63242338%3ffn%3dU29saXMgW0hETElHSFQgNzIwcF0gLSBGUkVOQ0g%3d%26rl%3da1&title=Solis%20%5bCOLOR%20coral%5dOpenload%5b%2fCOLOR%5d%20
2019-02-28 23:19:56.195 T:5886   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=Display_protected_link&sCat=1&sMovieTitle=Solis&sThumb=https%3a%2f%2fwawacity.ec%2f%2fimg%2ffilms%2ff4f34e27fe34232433bbfb6fc24edfc1.jpg&site=wawacity&siteUrl=https%3a%2f%2fwlnk.ec%2f63242338%3ffn%3dU29saXMgW0hETElHSFQgNzIwcF0gLSBGUkVOQ0g%3d%26rl%3da1&title=Solis%20%5bCOLOR%20coral%5dOpenload%5b%2fCOLOR%5d%20) failed
2019-02-28 23:19:59.865 T:9537  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
2019-02-28 23:20:00.025 T:9537  NOTICE: 	[PLUGIN] Vstream: load site wawacity and call function Display_protected_link
2019-02-28 23:20:00.426 T:9537  NOTICE: 	[PLUGIN] Vstream: could not load site: wawacity error: list index out of range
2019-02-28 23:20:00.427 T:9537   ERROR: Traceback (most recent call last):
2019-02-28 23:20:00.427 T:9537   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 139, in parseUrl
2019-02-28 23:20:00.428 T:9537   ERROR:     function()
2019-02-28 23:20:00.428 T:9537   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/sites/wawacity.py", line 780, in Display_protected_link
2019-02-28 23:20:00.430 T:9537   ERROR:     sHtmlContent = DecryptddlProtect(sUrl)
2019-02-28 23:20:00.430 T:9537   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/sites/wawacity.py", line 844, in DecryptddlProtect
2019-02-28 23:20:00.431 T:9537   ERROR:     if host in s[0]:
2019-02-28 23:20:00.431 T:9537   ERROR: IndexError: list index out of range
2019-02-28 23:20:00.460 T:9537  NOTICE: 	[PLUGIN] Vstream: Table initialized
2019-02-28 23:20:00.530 T:9537 WARNING: CPythonInvoker(24, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2019-02-28 23:20:00.539 T:9536   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=Display_protected_link&sCat=1&sMovieTitle=Solis&sThumb=https%3a%2f%2fwawacity.ec%2f%2fimg%2ffilms%2ff4f34e27fe34232433bbfb6fc24edfc1.jpg&site=wawacity&siteUrl=https%3a%2f%2fwlnk.ec%2f1058e040%3ffn%3dU29saXMgW0hETElHSFQgNzIwcF0gLSBGUkVOQ0g%3d%26rl%3da1&title=Solis%20%5bCOLOR%20coral%5dVidoza%5b%2fCOLOR%5d%20
2019-02-28 23:20:00.543 T:5886   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=Display_protected_link&sCat=1&sMovieTitle=Solis&sThumb=https%3a%2f%2fwawacity.ec%2f%2fimg%2ffilms%2ff4f34e27fe34232433bbfb6fc24edfc1.jpg&site=wawacity&siteUrl=https%3a%2f%2fwlnk.ec%2f1058e040%3ffn%3dU29saXMgW0hETElHSFQgNzIwcF0gLSBGUkVOQ0g%3d%26rl%3da1&title=Solis%20%5bCOLOR%20coral%5dVidoza%5b%2fCOLOR%5d%20) failed
2019-02-28 23:20:02.153 T:9541  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
2019-02-28 23:20:02.308 T:9541  NOTICE: 	[PLUGIN] Vstream: load site wawacity and call function Display_protected_link
2019-02-28 23:20:02.732 T:9541  NOTICE: 	[PLUGIN] Vstream: could not load site: wawacity error: list index out of range
2019-02-28 23:20:02.732 T:9541   ERROR: Traceback (most recent call last):
2019-02-28 23:20:02.732 T:9541   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 139, in parseUrl
2019-02-28 23:20:02.734 T:9541   ERROR:     function()
2019-02-28 23:20:02.734 T:9541   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/sites/wawacity.py", line 780, in Display_protected_link
2019-02-28 23:20:02.736 T:9541   ERROR:     sHtmlContent = DecryptddlProtect(sUrl)
2019-02-28 23:20:02.736 T:9541   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/sites/wawacity.py", line 844, in DecryptddlProtect
2019-02-28 23:20:02.737 T:9541   ERROR:     if host in s[0]:
2019-02-28 23:20:02.737 T:9541   ERROR: IndexError: list index out of range
2019-02-28 23:20:02.762 T:9541  NOTICE: 	[PLUGIN] Vstream: Table initialized
2019-02-28 23:20:02.831 T:9541 WARNING: CPythonInvoker(25, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2019-02-28 23:20:02.841 T:9540   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=Display_protected_link&sCat=1&sMovieTitle=Solis&sThumb=https%3a%2f%2fwawacity.ec%2f%2fimg%2ffilms%2ff4f34e27fe34232433bbfb6fc24edfc1.jpg&site=wawacity&siteUrl=https%3a%2f%2fwlnk.ec%2ff52c8227%3ffn%3dU29saXMgW0hETElHSFQgNzIwcF0gLSBGUkVOQ0g%3d%26rl%3da1&title=Solis%20%5bCOLOR%20coral%5dMyStream%5b%2fCOLOR%5d%20
2019-02-28 23:20:02.852 T:5886   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=Display_protected_link&sCat=1&sMovieTitle=Solis&sThumb=https%3a%2f%2fwawacity.ec%2f%2fimg%2ffilms%2ff4f34e27fe34232433bbfb6fc24edfc1.jpg&site=wawacity&siteUrl=https%3a%2f%2fwlnk.ec%2ff52c8227%3ffn%3dU29saXMgW0hETElHSFQgNzIwcF0gLSBGUkVOQ0g%3d%26rl%3da1&title=Solis%20%5bCOLOR%20coral%5dMyStream%5b%2fCOLOR%5d%20) failed
2019-02-28 23:20:24.347 T:5886 WARNING: RunScript called for a non-script addon 'plugin.video.vstream'. This behaviour is deprecated.
2019-02-28 23:20:24.601 T:9545  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
2019-02-28 23:20:24.739 T:9545  NOTICE: 	[PLUGIN] Vstream: load site globalRun and call function uplog
2019-02-28 23:20:24.786 T:9545  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine

**Comment by f3n3k** [comment]
A priori après application du patch que Ludopotte a mis à dispo sur son github, le soucis est résolu.

**Comment by AzeRim** [comment]
@f3n3k C'était déjà corrigé dans la version bêta ou il faudra attendre la mise à jour 0.7.1
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/6ed73bac24a18555886594a66d4eb1b41a28260f#diff-e68656ac6d92e40b12c519d089d1d6b6
https://github.com/Kodi-vStream/venom-xbmc-addons/releases
