### ISSUE TITLE
ZONE TELECHARGEMENT

### ISSUE THREAD

**Issue by ludopotte** [Kodi-vStream/venom-xbmc-addons#2503]
Zone Telechargement ne marche plus quand on veux aller sur les Rubrique que par contre vidéos sélectionnée en Favoris marche. Que peux ton faire ?

**Comment by AzeRim** [comment]
Fonctionne avec la 0.7.2 en insistant un peu mais plus avec la bêta depuis hier. Je me trompe peut-être mais fonctionne pour moi actuellement avec la 0.7.2.

**Comment by Che-debarras** [comment]
Pourquoi la source zonetelechargement n'utilise pas le site ht tps://www.zonetelechargement.site/homep.html au lieu d'annuaire-telechargement ?

Il semble plus mise à jour et peut-être moins de souci? 

Voire l'intégrer au source?

**Comment by Che-debarras** [comment]
C'est résolu le problème de ZT

**Comment by mannou78** [comment]
ZT marche pas pour moi une fois arrive sur un lien je le selectionne mais le lien video ne s affiche jamais et sur l ecran ca continue d ecrire working ca spin et aucun lien ne  affiche

Merci pour l aide

**Comment by isandard** [comment]
Depuis quelques jours sur ZT j'ai le même probleme de spin et retour au menu, même les fils ne s'affichent plus ( films ==> nouveautés, ca marque en cours et puis plus rien )
d'apres ce que je lis dans les logs il s'agirait de urlllib qui a un soucis mais je ne sais pas où trouver une version à jour )

https://slexy.org/view/s21TYjSirC

> 2019-05-10 10:23:49.019 T:19152  NOTICE: 	[PLUGIN] Vstream: could not load site: zone_telechargement_ws error: unknown url type: nouveaute/
2019-05-10 10:23:49.019 T:19152   ERROR: Traceback (most recent call last):
2019-05-10 10:23:49.019 T:19152   ERROR:   File "C:\Users\eva-i5\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 139, in parseUrl
2019-05-10 10:23:49.020 T:19152   ERROR:     function()
2019-05-10 10:23:49.020 T:19152   ERROR:   File "C:\Users\eva-i5\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites\zone_telechargement_ws.py", line 393, in showMovies
2019-05-10 10:23:49.020 T:19152   ERROR:     sHtmlContent = oRequestHandler.request()
2019-05-10 10:23:49.020 T:19152   ERROR:   File "C:\Users\eva-i5\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler\requestHandler.py", line 96, in request
2019-05-10 10:23:49.020 T:19152   ERROR:     return self.__callRequest()
2019-05-10 10:23:49.020 T:19152   ERROR:   File "C:\Users\eva-i5\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler\requestHandler.py", line 139, in __callRequest
2019-05-10 10:23:49.020 T:19152   ERROR:     oResponse = urllib2.urlopen(oRequest, timeout = self.__timeout)
2019-05-10 10:23:49.020 T:19152   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 154, in urlopen
2019-05-10 10:23:49.020 T:19152   ERROR:     return opener.open(url, data, timeout)
2019-05-10 10:23:49.020 T:19152   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 421, in open
2019-05-10 10:23:49.020 T:19152   ERROR:     protocol = req.get_type()
2019-05-10 10:23:49.020 T:19152   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 283, in get_type
2019-05-10 10:23:49.020 T:19152   ERROR:     raise ValueError, "unknown url type: %s" % self.__original
2019-05-10 10:23:49.020 T:19152   ERROR: ValueError: unknown url type: nouveaute/

**Comment by isandard** [comment]
bon maintenant ca remarche, va savoir pourquoi

**Comment by Arias800** [comment]
Problème de surcharge car en fait Vstream cherche a recuperer la redirection hors des fois le site renvoie rien ce qui fait que Vstream cherche a ce connecter avec aucun nom de domain du coup j'ai essayer une correction pour voir ^^
