### ISSUE TITLE
 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by Tetdoss** [Kodi-vStream/venom-xbmc-addons#2840]
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.vstream/default.py", line 6, in <module>
                                                from resources.lib.gui.hoster import cHosterGui
                                              File "/home/pi/.kodi/addons/plugin.video.vstream/resources/lib/gui/hoster.py", line 4, in <module>
                                                from resources.lib.gui.gui import cGui
                                              File "/home/pi/.kodi/addons/plugin.video.vstream/resources/lib/gui/gui.py", line 4, in <module>
                                                from resources.lib.gui.guiElement import cGuiElement
                                              File "/home/pi/.kodi/addons/plugin.video.vstream/resources/lib/gui/guiElement.py", line 16, in <module>
                                                class cGuiElement:
                                              File "/home/pi/.kodi/addons/plugin.video.vstream/resources/lib/gui/guiElement.py", line 21, in cGuiElement
                                                DB = cDb()
                                              File "/home/pi/.kodi/addons/plugin.video.vstream/resources/lib/db.py", line 39, in __init__
                                                VSlog('Erreur: Impossible d\'écrire sur %s' % self.REALDB )
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
                                            -->End of Python script error report<--

**Comment by sizanic** [comment]
Bonjour pour commencer,

et une petite description de quand cela se produit pourrait vraiment nous aider.

Même si j'ai déjà la réponse, regarde ici : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2829

Problème déjà réglé.

**Comment by sizanic** [comment]
Pour la prochaine fois : 
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/new?template=bug.md

**Comment by UnixSafe** [comment]
j'ai le même problème dès que je lance  Vstream voici les logs je trouce aucune solutiion :/ 

2020-04-16 14:07:37.546 T:123145305600000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/Users/monusername/Library/Application Support/Kodi/addons/plugin.video.vstream/default.py", line 6, in <module>
                                                from resources.lib.gui.hoster import cHosterGui
                                              File "/Users/monusername/Library/Application Support/Kodi/addons/plugin.video.vstream/resources/lib/gui/hoster.py", line 4, in <module>
                                                from resources.lib.gui.gui import cGui
                                              File "/Users/monusername/Library/Application Support/Kodi/addons/plugin.video.vstream/resources/lib/gui/gui.py", line 4, in <module>
                                                from resources.lib.gui.guiElement import cGuiElement
                                              File "/Users/monusername/Library/Application Support/Kodi/addons/plugin.video.vstream/resources/lib/gui/guiElement.py", line 16, in <module>
                                                class cGuiElement:
                                              File "/Users/monusername/Library/Application Support/Kodi/addons/plugin.video.vstream/resources/lib/gui/guiElement.py", line 21, in cGuiElement
                                                DB = cDb()
                                              File "/Users/monusername/Library/Application Support/Kodi/addons/plugin.video.vstream/resources/lib/db.py", line 39, in __init__
                                                VSlog('Erreur: Impossible d\'écrire sur %s' % self.REALDB )
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-04-16 14:07:37.570 T:123145303990272   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/
2020-04-16 14:07:37.570 T:140735294263296   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/) failed
2020-04-16 14:07:38.464 T:123145303453696 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)

**Comment by sizanic** [comment]
Tu ne trouves pas de solution alors qu'un sujet sur deux ici ne traite que de ça : 

#2842 - impossible d'installer Vstream depuis 2 jours
#2858 - installer vStream
#2857 - Fresh install KO
#2845 - erreur db.py à l'ouverture de vStream
#2829 - Bug avec OSMC - Kodi 18.6
https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2840#issuecomment-611264524 - ici même, dans ma première réponse.

La solution est d'ouvrir la fenêtre des paramètres de l'extension et d'appuyer sur 'D'origine' en bas à droite.

Ou d'installer la version 0.7.7 ici : https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.7.7

La mise à jour se fera toute seule si tu as installé le repository vStream.

**Comment by UnixSafe** [comment]
Merci pour ta réponse rapide. 
Entre temps j'ai installé la version bêta qui fonctionne parfaitement.
 J'ai bien installé le repository :)
