### ISSUE TITLE
Bug de lancement

### ISSUE THREAD

**Issue by osmoze06** [Kodi-vStream/venom-xbmc-addons#2859]
Boonjour, je ne parviens pas à faire fonctionner Vstream sur LibreElec, j'ai plusieurs messages d'erreurs au lancement, voici les logs : 

`2020-04-17 13:08:54.193 T:1423958912  NOTICE: 	[PLUGIN] vStream: SQLITE 3 as DB engine
2020-04-17 13:08:54.206 T:1423958912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vstream/default.py", line 6, in <module>
                                                from resources.lib.gui.hoster import cHosterGui
                                              File "/storage/.kodi/addons/plugin.video.vstream/resources/lib/gui/hoster.py", line 4, in <module>
                                                from resources.lib.gui.gui import cGui
                                              File "/storage/.kodi/addons/plugin.video.vstream/resources/lib/gui/gui.py", line 4, in <module>
                                                from resources.lib.gui.guiElement import cGuiElement
                                              File "/storage/.kodi/addons/plugin.video.vstream/resources/lib/gui/guiElement.py", line 16, in <module>
                                                class cGuiElement:
                                              File "/storage/.kodi/addons/plugin.video.vstream/resources/lib/gui/guiElement.py", line 21, in cGuiElement
                                                DB = cDb()
                                              File "/storage/.kodi/addons/plugin.video.vstream/resources/lib/db.py", line 39, in __init__
                                                VSlog('Erreur: Impossible d\'écrire sur %s' % self.REALDB )
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-04-17 13:08:54.309 T:1807721344   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/
2020-04-17 13:08:54.313 T:1937426880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/) failed
`

Je tourne sur la dernière version de LibreElec sur un Raspberry Pi 3.

Merci pour votre aide,

**Comment by TmpName** [comment]
Oui désolé, ya eu un loupage https://github.com/Kodi-vStream/venom-xbmc-addons/issues/2840#issuecomment-614846781

**Comment by osmoze06** [comment]
Merci pour cette réponse, je viens de mettre la version 0.7.7, c'est OK, mise a jour en cours ;-)

**Comment by Che-debarras** [comment]
Est ce que vstream est compatible CoreElec (TF300T) ?

**Comment by osmoze06** [comment]
Aucune idée. En tout cas, fonctionnel à 100% sur Raspberry Pi (avec OS : OSMC ou  LibreElect) sur Android et PC également.

**Comment by sizanic** [comment]
@osmoze06  je clos ton sujet, celui-ci a déjà été trop souvent abordé :

#2840 - 'ascii' codec can't decode byte
#2845 - erreur db.py à l'ouverture de vStream
#2842 - impossible d'installer Vstream depuis 2 jours
#2858 - installer vStream
#2857 - Fresh install KO
#2829 - Bug avec OSMC - Kodi 18.6
