### ISSUE TITLE
1fichier: impossible d'ouvrir un dossier qui contient 2000 liens

### ISSUE THREAD

**Issue by KoRnEr007** [Kodi-vStream/venom-xbmc-addons#3076]
**Décrivez le bug**
Quand je tente d'ouvrir le dossier mon compte 1fichier, ce dernier comprend 2200 liens.
Quand je clique dessus, je vois la barre de progression puis elle disparait et le dossier ne s'ouvre pas.
Si j'essaye avec un autre dossier 1fichier contenant moins de liens, il arrive à l'ouvrir

**Votre system**
 - OS: Android
-  Appareil nvidia shield
 - Version Kodi  18
- Version Vstream derniere béta (mais bug sans la béta aussi)

**Nous devons le reproduire**
Avoir un compte 1fichier
Avoir un répertoire dans 1fichier contenant + de 2000 liens
Dans vstream, allez sur moncompte 1fichier 
Ouvrir ce repertoire

**Comment by KoRnEr007** [comment]
I join errors on the kodi.log

`2020-10-07 14:21:09.785 T:13706  NOTICE: 	[PLUGIN] vStream: could not load site: siteonefichier error: 'utf8' codec can't decode byte 0xe9 in position 13: invalid continuation byte
2020-10-07 14:21:09.785 T:13706   ERROR: Traceback (most recent call last):
2020-10-07 14:21:09.785 T:13706   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 191, in parseUrl
2020-10-07 14:21:09.785 T:13706   ERROR:     function()
2020-10-07 14:21:09.786 T:13706   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/sites/siteonefichier.py", line 93, in showFile
2020-10-07 14:21:09.788 T:13706   ERROR:     oGui.addDir(SITE_IDENTIFIER, 'showHosters', aEntry[2], 'genres.png', oOutputParameterHandler)
2020-10-07 14:21:09.788 T:13706   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/gui/gui.py", line 214, in addDir
2020-10-07 14:21:09.791 T:13706   ERROR:     oGuiElement.setTitle(sLabel)
2020-10-07 14:21:09.791 T:13706   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/gui/guiElement.py", line 314, in setTitle
2020-10-07 14:21:09.793 T:13706   ERROR:     self.__sTitle = self.TraiteTitre(sTitle)
2020-10-07 14:21:09.793 T:13706   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/gui/guiElement.py", line 263, in TraiteTitre
2020-10-07 14:21:09.793 T:13706   ERROR:     self.__sTitleWatched = self.str_conv(sTitle).replace(' ', '')
2020-10-07 14:21:09.793 T:13706   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/gui/guiElement.py", line 413, in str_conv
2020-10-07 14:21:09.793 T:13706   ERROR:     data = data.decode('utf8')
2020-10-07 14:21:09.793 T:13706   ERROR:   File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/encodings/utf_8.py", line 16, in decode
2020-10-07 14:21:09.793 T:13706   ERROR: UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 13: invalid continuation byte
2020-10-07 14:21:09.879 T:13705   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=showFile&sFav=showFile&sTitle=FILMS_HD&site=siteonefichier&siteUrl=https%3a%2f%2f1fichier.com%2fconsole%2ffiles.pl%3fdir_id%3d2791178%26oby%3d0%26search%3d&title=FILMS_HD
2020-10-07 14:21:09.881 T:13635   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showFile&sFav=showFile&sTitle=FILMS_HD&site=siteonefichier&siteUrl=https%3a%2f%2f1fichier.com%2fconsole%2ffiles.pl%3fdir_id%3d2791178%26oby%3d0%26search%3d&title=FILMS_HD) failed`

**Comment by milkibreizh** [comment]
@KoRnEr007 
**si cela marchait avant** 
regarde le titre des derniers liens que tu as ajoutés car il est peu être possible que le titre de la vidéo d'un de tes liens comporte un charactere spécial qui provoque une erreur de décodage.

**Comment by KoRnEr007** [comment]
j'ai jamais essayé en fait, ca fonctionne avec uptobox mais pas avec 1fichier

**Comment by KoRnEr007** [comment]
Je fermer l'issue ;) un encodage pas bon dans un fichier
Merci
