### ISSUE TITLE
Probleme tmdb et trakt pour ouvrir mes listes trakt

### ISSUE THREAD

**Issue by toadnam** [Kodi-vStream/venom-xbmc-addons#3105]
Bonjour,

Je vais essayer d'expliquer mon problème, je suis presque sûr que c'est pas grand chose mais je trouve pas... :-(

Si j'installe la version 4.0.26 j'ai plus accès à trakt ni au dossier themoviedb mais je peux lire depuis tmdb helper films popular mulan play with pastebin ou recherche with pastbin.

Message d erreur quand je veux ouvrir le dossier themoviedb dans themoviedb helper :

2020-11-01 13:23:05.439 T:3840  NOTICE: Previous line repeats 3 times.
2020-11-01 13:23:05.439 T:3840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\plugin.py", line 9, in <module>
                                                Container().router()
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\items\container.py", line 404, in router
                                                return self.get_directory()
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\items\container.py", line 369, in get_directory
                                                items = self.get_items(**self.params)
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\items\container.py", line 366, in get_items
                                                return self.list_basedir(info)
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\items\basedir.py", line 640, in list_basedir
                                                return _get_basedir_list(None, tmdb=True)
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\items\basedir.py", line 34, in _get_basedir_list
                                                return _build_basedir(item_type, basedir)
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\items\basedir.py", line 19, in _build_basedir
                                                item['label'] = i.get('label', '').format(space=space, item_type=plural)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-11-01 13:23:05.477 T:9528   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=dir_tmdb
2020-11-01 13:23:05.482 T:4556   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.themoviedb.helper/?info=dir_tmdb) failed

Message d erreur quand je veux ouvrir le dossier trakt dans themoviedb helper :

020-11-01 13:26:04.873 T:10676  NOTICE: [plugin.video.themoviedb.helper]
                                            Getting KodiDB movie FAILED!
2020-11-01 13:27:00.539 T:4040   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\plugin.py", line 9, in <module>
                                                Container().router()
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\items\container.py", line 404, in router
                                                return self.get_directory()
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\items\container.py", line 369, in get_directory
                                                items = self.get_items(**self.params)
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\items\container.py", line 366, in get_items
                                                return self.list_basedir(info)
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\items\basedir.py", line 642, in list_basedir
                                                return _get_basedir_list(None, trakt=True)
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\items\basedir.py", line 34, in _get_basedir_list
                                                return _build_basedir(item_type, basedir)
                                              File "C:\KodiPortable2\App\Kodi\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\items\basedir.py", line 19, in _build_basedir
                                                item['label'] = i.get('label', '').format(space=space, item_type=plural)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-11-01 13:27:00.582 T:6496   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=dir_trakt
2020-11-01 13:27:00.585 T:4556   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.themoviedb.helper/?info=dir_trakt) failed

quand j'installe la version officielle depuis le depot kodi 2.4.36, j'ai accès au dossier trakt mais rien ne se lance depuis ma liste.

2020-11-01 13:35:15.334 T:4556   ERROR: Control 500 in window 10025 has been asked to focus, but it can't
2020-11-01 13:35:31.668 T:4556  NOTICE: VideoPlayer::OpenFile: '"plugin://plugin.video.themoviedb.helper/?info=play&fanarttv=True&type=movie&nextpage=True&tmdb_id=330457"'
2020-11-01 13:35:31.669 T:148  NOTICE: Creating InputStream
2020-11-01 13:35:31.669 T:148 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol('"plugin) in '"plugin://plugin.video.themoviedb.helper/?info=play&fanarttv=True&type=movie&nextpage=True&tmdb_id=330457"'
2020-11-01 13:35:31.669 T:148   ERROR: CVideoPlayer::OpenInputStream - error opening ['"plugin://plugin.video.themoviedb.helper/?info=play&fanarttv=True&type=movie&nextpage=True&tmdb_id=330457"']
2020-11-01 13:35:31.669 T:148  NOTICE: CVideoPlayer::OnExit()
2020-11-01 13:35:31.776 T:4556  NOTICE: CVideoPlayer::CloseFile()
2020-11-01 13:35:31.776 T:4556  NOTICE: VideoPlayer: waiting for threads to exit
2020-11-01 13:35:31.776 T:4556  NOTICE: VideoPlayer: finished waiting

Pouvez-vous m'aider et me dire sur quelle version je dois rester?

Par avance merci

**Comment by Arias800** [comment]
Vstream n'utilise pas themoviedb.helper, donc ont ne va rien n'y faire. Il faut voir avec le créateur de l'addon directement.

**Comment by toadnam** [comment]
@Arias800 je suis d'accord avec toi mais Jvoulais un petit coup de main de la part de la communauté 😉
Je vais essayer de trouver un autre endroit pour demander, désolé pour la gêne occasionnée.

**Comment by Arias800** [comment]
Pas de soucis, si tu veux contacter le développeur c'est ici: https://github.com/jurialmunkey/plugin.video.themoviedb.helper

D'ailleurs il y a deja un poste d'@alKODIque avec un sujet similaire : https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/331

**Comment by toadnam** [comment]
Super merci beaucoup ! Je vais y jeter un œil et encore bravo pour tout le taf de l'équipe !
