### ISSUE TITLE
Recherche visuelle ne fonctionne pas avec des caractères accentués

### ISSUE THREAD

**Issue by mifrey00** [Kodi-vStream/venom-xbmc-addons#3109]
**Description**
Recherche visuelle (films, série ou acteurs) ne fonctionne pas avec des caractères accentués.

**Système**
- OSMC 2020.10-1 / Debian 10 (Buster) / Raspberry Pi
- Version Kodi 18.8
- Version Vstream 0.8.2

**Reproduire**
VStream ➔ Visual Search ➔ Search (TMDB) ➔ Search a movie ➔ <nom du film>, par exemple "les évadés"

**Log**
```
2020-11-15 12:24:12.063 T:1916507056   DEBUG: CDirectoryProvider[plugin://plugin.program.autocompletion?info=autocomplete&&id=évadés&&limit=9]: refreshing..
2020-11-15 12:24:12.064 T:708419808   DEBUG: Thread JobWorker start, auto delete: true
2020-11-15 12:24:12.065 T:708419808   DEBUG: StartScript - calling plugin AutoCompletion for virtual keyboard('plugin://plugin.program.autocompletion/','87','?info=autocomplete&&id=évadés&&limit=9','resume:false')
2020-11-15 12:24:12.066 T:716812512   DEBUG: Thread LanguageInvoker start, auto delete: false
2020-11-15 12:24:12.066 T:716812512    INFO: initializing python engine.
2020-11-15 12:24:12.066 T:716812512   DEBUG: CPythonInvoker(218, /home/osmc/.kodi/addons/plugin.program.autocompletion/plugin.py): start processing
2020-11-15 12:24:12.276 T:1916507056   DEBUG: ------ Window Deinit (DialogKeyboard.xml) ------
2020-11-15 12:24:12.371 T:1646227680   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Input.OnInputFinished  - data: null
2020-11-15 12:24:12.373 T:1637834976   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender xbmc - method: Input.OnInputFinished  - data: null
2020-11-15 12:24:12.387 T:716812512   DEBUG: -->Python Interpreter Initialized<--
2020-11-15 12:24:12.387 T:716812512   DEBUG: CPythonInvoker(218, /home/osmc/.kodi/addons/plugin.program.autocompletion/plugin.py): the source file to load is "/home/osmc/.kodi/addons/plugin.program.autocompletion/plugin.py"
2020-11-15 12:24:12.392 T:716812512   DEBUG: CPythonInvoker(218, /home/osmc/.kodi/addons/plugin.program.autocompletion/plugin.py): setting the Python path to /home/osmc/.kodi/addons/plugin.program.autocompletion:/home/osmc/.kodi/addons/script.module.autocompletion/lib:/home/osmc/.kodi/addons/script.module.simplejson/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
2020-11-15 12:24:12.392 T:716812512   DEBUG: CPythonInvoker(218, /home/osmc/.kodi/addons/plugin.program.autocompletion/plugin.py): entering source directory /home/osmc/.kodi/addons/plugin.program.autocompletion
2020-11-15 12:24:12.392 T:716812512   DEBUG: CPythonInvoker(218, /home/osmc/.kodi/addons/plugin.program.autocompletion/plugin.py): instantiating addon using automatically obtained id of "plugin.program.autocompletion" dependent on version 2.24.0 of the xbmc.python api
2020-11-15 12:24:12.394 T:796537056   DEBUG:    [PLUGIN] vStream: could not load site: themoviedb_org error: object of type 'bool' has no len()
2020-11-15 12:24:12.435 T:796537056   ERROR: Traceback (most recent call last):
2020-11-15 12:24:12.435 T:796537056   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.vstream/default.py", line 191, in parseUrl
2020-11-15 12:24:12.455 T:796537056   ERROR:     function()
2020-11-15 12:24:12.455 T:796537056   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.vstream/resources/sites/themoviedb_org.py", line 363, in showSearchMovie
2020-11-15 12:24:12.876 T:796537056   ERROR:     showMovies(sSearchText.replace(' ', '+'))
2020-11-15 12:24:12.876 T:796537056   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.vstream/resources/sites/themoviedb_org.py", line 514, in showMovies
2020-11-15 12:24:12.880 T:796537056   ERROR:     total = len(result)
2020-11-15 12:24:12.880 T:796537056   ERROR: TypeError: object of type 'bool' has no len()
2020-11-15 12:24:12.983 T:796537056    INFO: CPythonInvoker(217, /home/osmc/.kodi/addons/plugin.video.vstream/default.py): script successfully run
2020-11-15 12:24:12.984 T:796537056   DEBUG: onExecutionDone(217, /home/osmc/.kodi/addons/plugin.video.vstream/default.py)
2020-11-15 12:24:13.049 T:741990624   DEBUG: CWebServer[8080]: request received for /jsonrpc
2020-11-15 12:24:13.225 T:716812512   DEBUG: Previous line repeats 1 times.
2020-11-15 12:24:13.225 T:716812512   DEBUG: version 1.0.1 started
2020-11-15 12:24:13.581 T:716812512   DEBUG: CAddonSettings[plugin.program.autocompletion]: loading setting definitions
2020-11-15 12:24:13.581 T:716812512   DEBUG: CAddonSettings[plugin.program.autocompletion]: trying to load setting definitions from old format...
2020-11-15 12:24:13.590 T:796537056    INFO: Python interpreter stopped
2020-11-15 12:24:13.591 T:716812512   DEBUG: plugin.program.autocompletion: opened textfile /home/osmc/.kodi/userdata/addon_data/plugin.program.autocompletion/Google/0b37367b1fafa75118919217f5549705.txt.
2020-11-15 12:24:13.591 T:804929760   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=showSearchMovie&sFav=showSearchMovie&site=themoviedb_org&siteUrl=search%2fmovie&title=Search%20a%20Movie
2020-11-15 12:24:13.591 T:804929760   DEBUG: Thread waiting 804929760 terminating
2020-11-15 12:24:13.591 T:1916507056   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-11-15 12:24:13.591 T:796537056   DEBUG: Thread LanguageInvoker 796537056 terminating
2020-11-15 12:24:13.593 T:1916507056   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showSearchMovie&sFav=showSearchMovie&site=themoviedb_org&siteUrl=search%2fmovie&title=Search%20a%20Movie) failed
2020-11-15 12:24:13.594 T:1916507056   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.vstream/?function=showSearch&sFav=showSearch&site=themoviedb_org&siteUrl=http%3a%2f%2f&title=Search%20(TMDB))
2020-11-15 12:24:13.594 T:1916507056   DEBUG:   ParentPath = [plugin://plugin.video.vstream/?function=load&sFav=load&site=themoviedb_org&siteUrl=http%3a%2f%2fvenom&title=Visual%20search]
2020-11-15 12:24:13.594 T:716812512   DEBUG: plugin.program.autocompletion: loaded file for http://clients1.google.com/complete/search?hl=en&q=%C3%A9vad%C3%A9s&json=t&client=serp&ds=yt. time: 0.011464
2020-11-15 12:24:13.594 T:796537056   DEBUG: Thread JobWorker start, auto delete: true
2020-11-15 12:24:13.596 T:1916507056   DEBUG: Loading items: 3, directory: plugin://plugin.video.vstream/?function=showSearch&sFav=showSearch&site=themoviedb_org&siteUrl=http%3a%2f%2f&title=Search%20(TMDB) sort method: 0, ascending: false
2020-11-15 12:24:13.613 T:796537056   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.vstream] took 19 ms
2020-11-15 12:24:13.613 T:804929760   DEBUG: Thread JobWorker start, auto delete: true
2020-11-15 12:24:13.619 T:1039089888   DEBUG: Thread BackgroundLoader start, auto delete: false
2020-11-15 12:24:13.625 T:716812512   DEBUG: finished
2020-11-15 12:24:13.626 T:716812512    INFO: CPythonInvoker(218, /home/osmc/.kodi/addons/plugin.program.autocompletion/plugin.py): script successfully run
2020-11-15 12:24:13.626 T:716812512   DEBUG: onExecutionDone(218, /home/osmc/.kodi/addons/plugin.program.autocompletion/plugin.py)
2020-11-15 12:24:13.634 T:1039089888   DEBUG: Thread BackgroundLoader 1039089888 terminating
2020-11-15 12:24:14.030 T:716812512    INFO: Python interpreter stopped
2020-11-15 12:24:14.031 T:716812512   DEBUG: Thread LanguageInvoker 716812512 terminating
2020-11-15 12:24:14.719 T:741990624   DEBUG: CWebServer[8080]: request received for /jsonrpc
```

**Comment by Arias800** [comment]
C'est corrigé dans la beta : https://github.com/Kodi-vStream/venom-xbmc-addons/commit/88d5be63f522c17be7646179d9943a16335a9a6c

**Comment by mifrey00** [comment]
Ça c'est du rapide !  Je viens de tester ça marche :-)

Merci.
