### ISSUE TITLE
'unicodeescape' codec can't decode bytes

### ISSUE THREAD

**Issue by 0x0040** [Kodi-vStream/venom-xbmc-addons#3176]
**Décrivez le bug**
Impossible d'accéder à un lien à cause d'un caractère qui pose problème dans la page.

**Votre system**
 - OS: Linux (Fedora 33)
 - Version Kodi  19
- Version Vstream 0.8.4

**Nous devons le reproduire**
Sur ZT, Lost, Les disparus, saison 1, HD720p Multi

**Log**
2021-01-07 20:21:13.890 T:3372     INFO <general>: initializing python engine.
2021-01-07 20:21:13.957 T:3372     INFO <general>:      [PLUGIN] vStream: DB engine for db : sqlite3.dbapi2
2021-01-07 20:21:14.043 T:3372     INFO <general>:      [PLUGIN] vStream: load site zone_telechargement_ws and call function showSeriesLinks
2021-01-07 20:21:14.047 T:3372     INFO <general>:      [PLUGIN] vStream: SQLITE 3 as DB engine for tmdb
2021-01-07 20:21:14.048 T:3372     INFO <general>:      [PLUGIN] vStream: ZT pas besoin d'url
2021-01-07 20:21:16.296 T:3372     INFO <general>:      [PLUGIN] vStream: could not load site: zone_telechargement_ws error: 'unicodeescape' codec can't decode bytes in position 128230-128231: truncated \UXXXXXXXX escape
2021-01-07 20:21:16.298 T:3372    ERROR <general>: Traceback (most recent call last):

2021-01-07 20:21:16.298 T:3372    ERROR <general>:
2021-01-07 20:21:16.298 T:3372    ERROR <general>:   File "/home/xxx/.kodi/addons/plugin.video.vstream/default.py", line 191, in parseUrl
                                                       function()

2021-01-07 20:21:16.298 T:3372    ERROR <general>:
2021-01-07 20:21:16.298 T:3372    ERROR <general>:   File "/home/xxx/.kodi/addons/plugin.video.vstream/resources/sites/zone_telechargement_ws.py", line 579, in showSeriesLinks
                                                       sHtmlContent = Stormwall().GetHtml(RestUrl + "?_token" + token)

2021-01-07 20:21:16.298 T:3372    ERROR <general>:
2021-01-07 20:21:16.298 T:3372    ERROR <general>:   File "/home/xxx/.kodi/addons/plugin.video.vstream/resources/lib/stormwall.py", line 99, in GetHtml
                                                       htmlcontent = self.htmlrequest(url, cookies, data)

2021-01-07 20:21:16.298 T:3372    ERROR <general>:
2021-01-07 20:21:16.298 T:3372    ERROR <general>:   File "/home/xxx/.kodi/addons/plugin.video.vstream/resources/lib/stormwall.py", line 128, in htmlrequest
                                                       sHtmlContent = oRequestHandler.request()

2021-01-07 20:21:16.298 T:3372    ERROR <general>:
2021-01-07 20:21:16.298 T:3372    ERROR <general>:   File "/home/xxx/.kodi/addons/plugin.video.vstream/resources/lib/handler/requestHandler.py", line 94, in request
                                                       return self.__callRequest()

2021-01-07 20:21:16.298 T:3372    ERROR <general>:
2021-01-07 20:21:16.298 T:3372    ERROR <general>:   File "/home/xxx/.kodi/addons/plugin.video.vstream/resources/lib/handler/requestHandler.py", line 166, in __callRequest
                                                       sContent = sContent.decode('unicode-escape')

2021-01-07 20:21:16.298 T:3372    ERROR <general>:
2021-01-07 20:21:16.298 T:3372    ERROR <general>: UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 128230-128231: truncated \UXXXXXXXX escape

2021-01-07 20:21:16.298 T:3372    ERROR <general>:
2021-01-07 20:21:16.300 T:3372     INFO <general>: CPythonInvoker(61, /home/xxx/.kodi/addons/plugin.video.vstream/default.py): script successfully run
2021-01-07 20:21:16.348 T:3372     INFO <general>: Python interpreter stopped
2021-01-07 20:21:16.361 T:3370    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vstream/?function=showSeriesLinks&sCat=2&sDisplayTitle=%20Lost%2c%20les%20disparus%20Saison%201%20%5bHD%20720p%5d%20%20(MULTI)&sMovieTitle=%20Lost%2c%20les%20disparus%20Saison%201&sThumb=https%3a%2f%2fwww.zone-images.com%2fuploads%2fdQiED.jpg&site=zone_telechargement_ws&siteUrl=https%3a%2f%2fzt-protect.net%2farticle%2fMTkzSWlKbno5M09DM2N6UXZJdlhuOHZ2b1ZZcmF1eXBsNDFXS2tyVUUyUnNDZTNOc05mbHI4WWwwdlYvdzNQaHh0Ti9ianZxemFtWW1Tb3EreGJtTldSQ1dDNTJSenR4RStjU2dVVDJhNVdzbXhEaEtBb2Vydm9MaGFkTHg5MGo%3d%2f14-1--&title=Lost%2c%20les%20disparus%20Saison%201
2021-01-07 20:21:16.366 T:2640    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showSeriesLinks&sCat=2&sDisplayTitle=%20Lost%2c%20les%20disparus%20Saison%201%20%5bHD%20720p%5d%20%20(MULTI)&sMovieTitle=%20Lost%2c%20les%20disparus%20Saison%201&sThumb=https%3a%2f%2fwww.zone-images.com%2fuploads%2fdQiED.jpg&site=zone_telechargement_ws&siteUrl=https%3a%2f%2fzt-protect.net%2farticle%2fMTkzSWlKbno5M09DM2N6UXZJdlhuOHZ2b1ZZcmF1eXBsNDFXS2tyVUUyUnNDZTNOc05mbHI4WWwwdlYvdzNQaHh0Ti9ianZxemFtWW1Tb3EreGJtTldSQ1dDNTJSenR4RStjU2dVVDJhNVdzbXhEaEtBb2Vydm9MaGFkTHg5MGo%3d%2f14-1--&title=Lost%2c%20les%20disparus%20Saison%201) failed

**Plus**
Le problème est dans le fichier "plugin.video.vstream/resources/lib/handler/requestHandler.py" à la ligne 165:
sContent = sContent.decode('unicode-escape')
Je ne sais pas si "unicode-escape" est essentiel mais si on laisse le "decode" par défaut (c'est à dire utf8) cela marche aussi bien:
sContent = sContent.decode()

**Comment by Arias800** [comment]
sContent.decode() ne fonctionne pas sous Kodi 18 et inférieure, je peu tester de mettre et voir si Kodi 18 ne bloque pas a la lecture.

**Comment by 0x0040** [comment]
Je crois que Kodi 18 et inférieure utilise python2.x, et Kodi 19 python 3.x...

Quoiqu'il en soit ce problème (qui n'apparait que sur certain lien) a été introduit ici https://github.com/Kodi-vStream/venom-xbmc-addons/commit/6bfc2a36e644a815f6515a03a2d7f7d2a43a54c2 et il semble que cela soit spécifique à python3 ou Kodi 19.

**Comment by Arias800** [comment]
C'est normalement corrigé dans la beta.
