### ISSUE TITLE
Kodi 19 Matrix

### ISSUE THREAD

**Issue by Niconimes** [Kodi-vStream/venom-xbmc-addons#3246]
Bonjour, j'ai vu que la dernière version de Kodi était officiellement sortie et que plusieurs changements ont été opérés notamment le langage Python 3 au lieu de Python 2.
Je voulais savoir si notre Addon préféré était prêt pour cette version ou si une installation allait poser des problèmes de compatibilité (Vstream et ses dépendances comme UrlResolver par exemple)?

**Comment by sylvain-schmitt** [comment]
J'ai eu une mise à jour de kodi qui est passer à kodi 19 matrix et vstream ne fonctionne plus donc pour l'instant il n'est pas compatible.
A moins que j'ai louper une mise à jour de l'addon je vais chekker ce soir si une nouvelle version de l'addon est dispo.

**Comment by Arias800** [comment]
Vstream est compatible, il y a déjà plusieurs personnes (en dehors de moi) qui l'ont testé sur plusieurs systèmes différents. Il faudrait les logs pour avoir plus d'informations.

**Comment by sylvain-schmitt** [comment]
Effectivement je viens de tester sur mon tel android tout est fonctionnel je regarde ce soir sur ma box si j'arrive a le faire fonctionné.

**Comment by Niconimes** [comment]
> Vstream est compatible, il y a déjà plusieurs personnes (en dehors de moi) qui l'ont testé sur plusieurs systèmes différents. Il faudrait les logs pour avoir plus d'informations.

Super, je vais tester la mise à jour ce soir dans ce cas 👍

**Comment by Niconimes** [comment]
Bon visiblement ça ne fonctionne pas je n'arrive plus à ouvrir aucun liens sur mon smartphone Android et je n'ai même plus accès à certaines options comme le fait d'activer ou non UrlResolver

**Comment by Niconimes** [comment]
![Screenshot_2021-02-23-18-53-26-258_org xbmc kodi](https://user-images.githubusercontent.com/43355451/108886761-a6ca6f80-7609-11eb-8d88-97419fd6d261.jpg)
![Screenshot_2021-02-23-18-53-47-062_org xbmc kodi](https://user-images.githubusercontent.com/43355451/108886769-a7fb9c80-7609-11eb-8e81-32d3738a4e6a.jpg)

**Comment by yas06** [comment]
salut je suis passer a matrix et vstream fonctionne j ai même réussi a remettre url resolver et  catch up tv
^par contre la migration de 18 a 19 des modules ne migre pas faut tout réinstaller

**Comment by Arias800** [comment]
Vstream n'a pas besoin d'être réinstaller grâce à une petite manipulation que j'ai trouvé (et qu'on est les seuls a utilisé a ma connaissance). Mais sinon oui pour les autres addons il faut installer les versions Kodi 19.
Je viens de testé sur mon téléphone Android et je n'arrive pas à reproduire le bug.
Essaye de nous donné un log pour voir si il n'y a pas d'erreur ou une indication sur l'origine du problème.

**Comment by sizanic** [comment]
Je ne pense pas qu'une version d'UrlResolver existe pour KODI19.

**Comment by yas06** [comment]
celui la fonctionne avec kodi19 
https://fusion.tvaddons.co/kodi-scripts/script.module.urlresolver-5.1.22.zip

**Comment by sylvain-schmitt** [comment]
Après réinstallation de Kodi et vstream tout est de nouveau fonctionnelle avec en prime le mode passtrough qui a l'air de fonctionner correctement maintenant alors qu'avant l'audio avait tendance à se décaler.

**Comment by Niconimes** [comment]
﻿2021-02-23 18:59:03.796 T:14045    INFO <general>: -----------------------------------------------------------------------
2021-02-23 18:59:03.796 T:14045    INFO <general>: Starting Kodi (19.0 (19.0.0) Git:20210218-f44fdfbf67). Platform: Android ARM 64-bit
2021-02-23 18:59:03.796 T:14045    INFO <general>: Using Release Kodi x64
2021-02-23 18:59:03.796 T:14045    INFO <general>: Kodi compiled 2021-02-18 by Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) for Android ARM 64-bit API level 21 (API level 21)
2021-02-23 18:59:03.796 T:14045    INFO <general>: Running on Xiaomi Redmi Note 7 with Android 10.0.0 API level 29, kernel: Linux ARM 64-bit version 4.4.192-perf+
2021-02-23 18:59:03.798 T:14045    INFO <general>: FFmpeg version/source: 4.3.1-Kodi
2021-02-23 18:59:03.798 T:14045    INFO <general>: 8 CPU cores available
2021-02-23 18:59:03.798 T:14045    INFO <general>: Product: lavender, Device: lavender, Board: sdm660 - Manufacturer: Xiaomi, Brand: xiaomi, Model: Redmi Note 7, Hardware: qcom
2021-02-23 18:59:03.803 T:14045    INFO <general>: External storage path = /storage/emulated/0; status = ok
2021-02-23 18:59:03.803 T:14045    INFO <general>: ARM Features: Neon disabled
2021-02-23 18:59:03.803 T:14045    INFO <general>: special://xbmc/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets
2021-02-23 18:59:03.803 T:14045    INFO <general>: special://xbmcbin/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets
2021-02-23 18:59:03.803 T:14045    INFO <general>: special://xbmcbinaddons/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets/addons
2021-02-23 18:59:03.803 T:14045    INFO <general>: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
2021-02-23 18:59:03.803 T:14045    INFO <general>: special://envhome/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files
2021-02-23 18:59:03.803 T:14045    INFO <general>: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
2021-02-23 18:59:03.803 T:14045    INFO <general>: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
2021-02-23 18:59:03.803 T:14045    INFO <general>: special://logpath/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
2021-02-23 18:59:03.803 T:14045    INFO <general>: The executable running is: /data/app/org.xbmc.kodi-2LcKs1-vB-cC-p2fJb6Idw==/lib/arm64/libkodi.so
2021-02-23 18:59:03.840 T:14045    INFO <general>: Local hostname: Android-3.home
2021-02-23 18:59:03.840 T:14045    INFO <general>: Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
2021-02-23 18:59:03.844 T:14045    INFO <general>: -----------------------------------------------------------------------
2021-02-23 18:59:03.854 T:14045    INFO <general>: loading settings
2021-02-23 18:59:03.857 T:14045    INFO <general>: special://profile/ is mapped to: special://masterprofile/
2021-02-23 18:59:03.870 T:14045    INFO <general>: No settings file to load (special://xbmc/system/advancedsettings.xml)
2021-02-23 18:59:03.870 T:14045    INFO <general>: No settings file to load (special://masterprofile/advancedsettings.xml)
2021-02-23 18:59:03.870 T:14045    INFO <general>: Default Video Player: VideoPlayer
2021-02-23 18:59:03.870 T:14045    INFO <general>: Default Audio Player: paplayer
2021-02-23 18:59:03.870 T:14045    INFO <general>: Disabled debug logging due to GUI setting. Level 0.
2021-02-23 18:59:03.870 T:14045    INFO <general>: Log level changed to "INFO"
2021-02-23 18:59:03.879 T:14045    INFO <general>: creating subdirectories
2021-02-23 18:59:03.880 T:14045    INFO <general>: userdata folder: special://masterprofile/
2021-02-23 18:59:03.880 T:14045    INFO <general>: recording folder:
2021-02-23 18:59:03.880 T:14045    INFO <general>: screenshots folder:
2021-02-23 18:59:03.898 T:14045    INFO <general>: Running database version Addons33
2021-02-23 18:59:04.154 T:14045    INFO <general>: CAddonMgr::FindAddons: audioencoder.kodi.builtin.aac v1.0.2 installed
2021-02-23 18:59:04.154 T:14045    INFO <general>: CAddonMgr::FindAddons: audioencoder.kodi.builtin.wma v1.0.2 installed
2021-02-23 18:59:04.155 T:14045    INFO <general>: CAddonMgr::FindAddons: game.controller.default v1.0.9 installed
2021-02-23 18:59:04.155 T:14045    INFO <general>: CAddonMgr::FindAddons: game.controller.snes v1.0.9 installed
2021-02-23 18:59:04.155 T:14045    INFO <general>: CAddonMgr::FindAddons: inputstream.adaptive v2.6.7 installed
2021-02-23 18:59:04.156 T:14045    INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.audioengine v1.1.1 installed
2021-02-23 18:59:04.156 T:14045    INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.filesystem v1.1.6 installed
2021-02-23 18:59:04.157 T:14045    INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.general v1.0.5 installed
This paste is large and only partially shown.
View full paste

View raw paste		Reply

 
Slexy.org Pastebin © 2021 · Terms of Service · v2.1.1

**Comment by Niconimes** [comment]
> Vstream n'a pas besoin d'être réinstaller grâce à une petite manipulation que j'ai trouvé (et qu'on est les seuls a utilisé a ma connaissance). Mais sinon oui pour les autres addons il faut installer les versions Kodi 19.
> Je viens de testé sur mon téléphone Android et je n'arrive pas à reproduire le bug.
> Essaye de nous donné un log pour voir si il n'y a pas d'erreur ou une indication sur l'origine du problème.

Voilà pour mon log, par contre je veux bien connaître ta "petite manip"

**Comment by Arias800** [comment]
Il faut nous donner l'id était affiché dans la boite de dialogue, car là les logs ne sont pas entier (et vu leurs longeure c'est pas une bonne idée de le posté sur Github).

L'astuce se situe dans le fichier addon.xml, Kodi tente de chargé l'addon en version Kodi 19 pour finalement chargé la version inférieure si ça échoue. Voilà le code en question : 
```
        <trycatch>
            <try>
                <import addon="xbmc.python" version="3.0.0"/>
            </try>

            <catch>
                <import addon="xbmc.python" version="2.24.0"/>
            </catch>
        </trycatch>
```

**Comment by Niconimes** [comment]
> Il faut nous donner l'id était affiché dans la boite de dialogue, car là les logs ne sont pas entier (et vu leurs longeure c'est pas une bonne idée de le posté sur Github).
> 
> L'astuce se situe dans le fichier addon.xml, Kodi tente de chargé l'addon en version Kodi 19 pour finalement chargé la version inférieure si ça échoue. Voilà le code en question :
> 
> ```
>         <trycatch>
>             <try>
>                 <import addon="xbmc.python" version="3.0.0"/>
>             </try>
> 
>             <catch>
>                 <import addon="xbmc.python" version="2.24.0"/>
>             </catch>
>         </trycatch>
> ```

C'est à dire le lien que j'avais vers Slexy?

**Comment by sizanic** [comment]
> C'est à dire le lien que j'avais vers Slexy?

oui

**Comment by Niconimes** [comment]
> > C'est à dire le lien que j'avais vers Slexy?
> 
> oui

https://slexy.org/raw/s21IZDuRtN?token=1c142e40682988709660f31efbc54164e895487f2ce04fed1dcf8bb0902ed340&ts=1614106710

**Comment by Niconimes** [comment]
J'ai essayé de désinstaller et réinstaller Vstream, il manque toujours des dépendances du coup j'ai remis Kodi 18.9 au moins tout fonctionne, on verra plus tard pour ce dernier Kodi

**Comment by sizanic** [comment]
Un truc intéressant en tout cas dans ton log.

Je ne sais pas si quelqu'un pourra regarder (pour le corriger ou valider que c'est déjà corrigé dans la Beta):
(perso je ne suis pas dispo)

```
2021-02-23 18:59:59.687 T:14625    INFO <general>: 	[PLUGIN] vStream: could not load site: wiflix error: can't concat str to bytes
2021-02-23 18:59:59.693 T:14625   ERROR <general>: Traceback (most recent call last):
                                                   
2021-02-23 18:59:59.694 T:14625   ERROR <general>: 
2021-02-23 18:59:59.694 T:14625   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 191, in parseUrl
                                                       function()
                                                   
2021-02-23 18:59:59.694 T:14625   ERROR <general>: 
2021-02-23 18:59:59.694 T:14625   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/sites/wiflix.py", line 373, in showHosters
                                                       oHoster.setDisplayName(sDisplaytitle)
                                                   
2021-02-23 18:59:59.694 T:14625   ERROR <general>: 
2021-02-23 18:59:59.694 T:14625   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/hosters/resolver.py", line 33, in setDisplayName
                                                       self.__sDisplayName = sDisplayName + ' [COLOR violet]'+ self.__sDisplayName + self.__sRealHost + '[/COLOR]'
                                                   
2021-02-23 18:59:59.694 T:14625   ERROR <general>: 
2021-02-23 18:59:59.694 T:14625   ERROR <general>: TypeError: can't concat str to bytes
                                                   
2021-02-23 18:59:59.694 T:14625   ERROR <general>: 
2021-02-23 18:59:59.704 T:14625    INFO <general>: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): script successfully run
2021-02-23 18:59:59.895 T:14625    INFO <general>: Python interpreter stopped
2021-02-23 18:59:59.911 T:14624   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vstream/?function=showHosters&sCat=1&sMovieTitle=Wrong%20Turn%20(2021)&sThumb=https%3a%2f%2fwww.wiflix.cc%2fcheckimg.php%3furli%3dhttps%3a%2f%2fzupimages.net%2fup%2f21%2f08%2fen0g.jpg&sYear=2021&site=wiflix&siteUrl=https%3a%2f%2fwiflix.cc%2ffilm-en-streaming%2f20622-wrong-turn-2021.html&title=Wrong%20Turn%20(2021)%20%5bHDLight%5d%20(French)
2021-02-23 18:59:59.920 T:14045   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showHosters&sCat=1&sMovieTitle=Wrong%20Turn%20(2021)&sThumb=https%3a%2f%2fwww.wiflix.cc%2fcheckimg.php%3furli%3dhttps%3a%2f%2fzupimages.net%2fup%2f21%2f08%2fen0g.jpg&sYear=2021&site=wiflix&siteUrl=https%3a%2f%2fwiflix.cc%2ffilm-en-streaming%2f20622-wrong-turn-2021.html&title=Wrong%20Turn%20(2021)%20%5bHDLight%5d%20(French)) failed
```

**Comment by Arias800** [comment]
C'est bon. Je sais d'où vient le problème, je le corrigerai en fin de semaine.
(C'est de ma faute j'ai pas penser à testé avec URL Resolver).

**Comment by yas06** [comment]
> C'est bon. Je sais d'où vient le problème, je le corrigerai en fin de semaine.
> (C'est de ma faute j'ai pas penser à testé avec URL Resolver).

Merci d avance je vais attendre ton correctif moi aussi avec urlresolver j ai pas de lien

**Comment by Arias800** [comment]
C'est corrigé dans la beta.

**Comment by Niconimes** [comment]
> C'est corrigé dans la beta.

Super je vais tester, merci

**Comment by yas06** [comment]
salut merci beaucoup ca marche reste 2 ,3 site qui marche pas mais il etait down avant la maj matrix
encore une fois MERCI @Arias800

**Comment by Niconimes** [comment]
> C'est corrigé dans la beta.

je confirme, merci Arias800, ça fonctionne très bien, merci encore pour ton boulot 👍
