### ISSUE TITLE
Erreur téléchargement

### ISSUE THREAD

**Issue by alexkitryp** [Kodi-vStream/venom-xbmc-addons#3287]
![Screenshot_20210504-222244_Kodi](https://user-images.githubusercontent.com/48083283/117065116-5701d600-ad27-11eb-951d-b261fed0a6bc.png)

Bonjour,

J'utilise kodi sur android 10. J'ai un souci avec la fonction "télécharger" ou "télécharger et lire" de vstream. Malgré que j'ai entièrement desinstallé Kodi puis réinstallé. Ensuite, réinstallé vstream depuis le repo officiel l'erreur persiste. La lecture fonctionne mais pas le telechargement. Parfois, j'ai aussi une erreur de type "téléchargement déjà démarré". Je n'utilise pas urlresolver ou de debrideur.

Kodi 19
Oneplus 3T
LineageOS 18.1 Android 10
Exemple, mais me le fait sur tout les fichiers :
Site cinemay
Série helstrom saison 1 épisode 4

Kodi.log : 
2021-05-04 21:58:49.818 T:25736    INFO <general>: initializing python engine.
2021-05-04 21:58:50.464 T:25736    INFO <general>: 	[PLUGIN] vStream: DB engine for db : sqlite3.dbapi2
2021-05-04 21:58:51.227 T:25736    INFO <general>: 	[PLUGIN] vStream: load site cDownload and call function AddtoDownloadListandview
2021-05-04 21:58:51.238 T:25736    INFO <general>: 	[PLUGIN] vStream: Download https://uqload.org/embed-y3cp0h3ssmqe.html
2021-05-04 21:58:51.252 T:25736   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: a bytes-like object is required, not 'str'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 372, in <module>
                                                       main()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 49, in __init__
                                                       self.parseUrl()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 143, in parseUrl
                                                       if isDl(sSiteName, sFunction):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 275, in isDl
                                                       exec("oDownload." + sFunction + "()")
                                                     File "<string>", line 1, in <module>
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 700, in AddtoDownloadListandview
                                                       if (self.AddDownload(meta)):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 619, in AddDownload
                                                       sTitle = self.__createTitle(sUrl, sTitle)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 344, in __createTitle
                                                       aTitle = sTitle.rsplit('.')
                                                   TypeError: a bytes-like object is required, not 'str'
                                                   -->End of Python script error report<--
                                                   
2021-05-04 21:58:51.513 T:25736    INFO <general>: Python interpreter stopped
2021-05-04 21:58:54.673 T:22583    INFO <general>: CWinSystemAndroid::DestroyWindow

Dés que je vais dans " outils -> telecharger ", j'ai également une erreur.

Kodi.log :
2021-05-04 22:15:39.318 T:27726   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vstream/?function=getDownload&sFav=getDownload&site=cDownload&siteUrl=http%3a%2f%2fvenom&title=T%c3%a9l%c3%a9charger
2021-05-04 22:15:39.321 T:27425   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=getDownload&sFav=getDownload&site=cDownload&siteUrl=http%3a%2f%2fvenom&title=T%c3%a9l%c3%a9charger) failed
2021-05-04 22:15:46.646 T:27737   ERROR <general>: Unable to find plugin 
2021-05-04 22:15:46.646 T:27737   ERROR <general>: GetDirectory - Error getting plugin://
2021-05-04 22:15:46.648 T:27425   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://) failed
2021-05-04 22:15:48.533 T:27425    INFO <general>: CWinSystemAndroid::DestroyWindow
2021-05-04 22:15:48.901 T:27398 WARNING <general>: CPeripheralBusAndroid: failed to update input device with ID 3 because it couldn't be found

Pouvez-vous m'aider ?

Merci d'avance pour vos retours.

**Comment by TmpName** [comment]
Je ne suis pas encore sous python3

Mais essayes cette modif

`aTitle = sTitle.rsplit('.')`

A modifier en 
```
try:
    aTitle = sTitle.rsplit('.')
except:
    aTitle = sTitle.decode().rsplit('.')
```

**Comment by alexkitryp** [comment]
Merci pour le retour, avec la modif, j'ai maintenant cette erreur : 
2021-05-06 23:48:24.119 T:13688    INFO <general>: initializing python engine.
2021-05-06 23:48:24.748 T:13688    INFO <general>: 	[PLUGIN] vStream: DB engine for db : sqlite3.dbapi2
2021-05-06 23:48:25.476 T:13688    INFO <general>: 	[PLUGIN] vStream: load site cDownload and call function AddtoDownloadListandview
2021-05-06 23:48:25.541 T:13688    INFO <general>: 	[PLUGIN] vStream: Download https://uqload.org/embed-y98mmome2kql.html
2021-05-06 23:48:25.554 T:13688   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: can't concat str to bytes
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 372, in <module>
                                                       main()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 49, in __init__
                                                       self.parseUrl()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 143, in parseUrl
                                                       if isDl(sSiteName, sFunction):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 275, in isDl
                                                       exec("oDownload." + sFunction + "()")
                                                     File "<string>", line 1, in <module>
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 704, in AddtoDownloadListandview
                                                       if (self.AddDownload(meta)):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 623, in AddDownload
                                                       sTitle = self.__createTitle(sUrl, sTitle)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 360, in __createTitle
                                                       sTitle = sTitle + '.mp4'  # Si quedale on en prend une au pif
                                                   TypeError: can't concat str to bytes
                                                   -->End of Python script error report<--

**Comment by TmpName** [comment]
Bon la ca commence a etre plus chaud que prevu, aucune idée si le code a besoin d'un str ou d'un unicode, essaye de transformer direct des le debut

```
    def __createTitle(self, sUrl, sTitle):

        sTitle = cUtil().CleanName(sTitle)
        sTitle = cUtil().FormatSerie(sTitle)
        
        if isMatrix():
            try:
                sTitle = sTitle.decode()
            except:
                pass

        aTitle = sTitle.rsplit('.')
    
        # Si deja extension
        if (len(aTitle) > 1):
            return sTitle

        # recherche d'une extension
        sUrl = sUrl.lower()

        m = re.search('(flv|avi|mp4|mpg|mpeg|mkv)', sUrl)
        if m:
            sTitle = sTitle + '.' + m.group(0)
        else:
            sTitle = sTitle + '.mp4'  # Si quedale on en prend une au pif

        return sTitle
```

**Comment by alexkitryp** [comment]
Merci pour le retour, avec la modif, j'ai maintenant cette erreur : 
2021-05-06 23:48:24.119 T:13688    INFO <general>: initializing python engine.
2021-05-06 23:48:24.748 T:13688    INFO <general>: 	[PLUGIN] vStream: DB engine for db : sqlite3.dbapi2
2021-05-06 23:48:25.476 T:13688    INFO <general>: 	[PLUGIN] vStream: load site cDownload and call function AddtoDownloadListandview
2021-05-06 23:48:25.541 T:13688    INFO <general>: 	[PLUGIN] vStream: Download https://uqload.org/embed-y98mmome2kql.html
2021-05-06 23:48:25.554 T:13688   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: can't concat str to bytes
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 372, in <module>
                                                       main()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 49, in __init__
                                                       self.parseUrl()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 143, in parseUrl
                                                       if isDl(sSiteName, sFunction):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 275, in isDl
                                                       exec("oDownload." + sFunction + "()")
                                                     File "<string>", line 1, in <module>
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 704, in AddtoDownloadListandview
                                                       if (self.AddDownload(meta)):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 623, in AddDownload
                                                       sTitle = self.__createTitle(sUrl, sTitle)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 360, in __createTitle
                                                       sTitle = sTitle + '.mp4'  # Si quedale on en prend une au pif
                                                   TypeError: can't concat str to bytes
                                                   -->End of Python script error report<--

**Comment by alexkitryp** [comment]
Encore merci d'essayer de m'aider. Bon comme prevu :) nouvelle erreur, suite la modif : 
2021-05-10 18:57:27.529 T:14411    INFO <general>: initializing python engine.
2021-05-10 18:57:28.183 T:14411    INFO <general>: 	[PLUGIN] vStream: DB engine for db : sqlite3.dbapi2
2021-05-10 18:57:28.987 T:14411    INFO <general>: 	[PLUGIN] vStream: load site cDownload and call function AddtoDownloadListandview
2021-05-10 18:57:29.058 T:14411    INFO <general>: 	[PLUGIN] vStream: Download https://uqload.org/embed-y3cp0h3ssmqe.html
2021-05-10 18:57:29.071 T:14411   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'isMatrix' is not defined
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 372, in <module>
                                                       main()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 49, in __init__
                                                       self.parseUrl()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 143, in parseUrl
                                                       if isDl(sSiteName, sFunction):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py", line 275, in isDl
                                                       exec("oDownload." + sFunction + "()")
                                                     File "<string>", line 1, in <module>
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 712, in AddtoDownloadListandview
                                                       if (self.AddDownload(meta)):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 631, in AddDownload
                                                       sTitle = self.__createTitle(sUrl, sTitle)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/download.py", line 349, in __createTitle
                                                       if isMatrix():
                                                   NameError: name 'isMatrix' is not defined
                                                   -->End of Python script error report<--
                                                   
2021-05-10 18:57:29.282 T:14411    INFO <general>: Python interpreter stopped

**Comment by sizanic** [comment]
@alexkitryp 
Tu as vraiment besoin de télécharger ?

Ce n'est pas une fonctionnalité que l'on souhaite maintenir.

**Comment by alexkitryp** [comment]
honnêtement, je trouve cette fonctionnalité très pratique et très intéressante. Notamment pour economiser des données mobiles par exemple. Après si vous ne comptiez pas la maintenir je ne vais pas vous demander des efforts supplémentaires, je comprendrais, à vous de voir.

**Comment by sizanic** [comment]
C'était juste pour t'expliquer pourquoi nous ne sommes pas très investis dans cette correction.

Par contre, je ne comprend pas ton exemple, car tu n'économises rien en téléchargeant d'abord le film pour le regarder ensuite, par rapport à le regarder directement en direct.
Tu téléchargeras la même quantité de donnée 🤔 

Sauf si tu comptes le regarder plusieurs fois en peu de temps.
Car si tu compte le regarder beaucoup plus tard, ça veux dire que tu vas devoir stocker beaucoup de films dans ce cas.
Donc tu te refais en local une copie des films déjà disponibles à volonté sur internet.


Et je te confirme que ce n'est pas l'objectif de vStream de servir d'outil de téléchargement.
Il ne s'agit pas de vDownload mais de vStream 😉

**Comment by alexkitryp** [comment]
Ah ah je comprends bien votre position pas de souci.
Je télécharge quand je suis en Wi-Fi et oui je regarfe en plusieurs fois, j'ai une méchante tendance a m'endormir devant ;) et ça ne me gêne pas de stocker 5-6 épisodes d'une série. Ça m'a permis aussi de trouver des films que j'avais parfois du mal a trouver en streaming. Et d'être sur des les retrouver quand je voulais les recours plusieurs semaines ou mois plus tard. Encore une fois pas de souci, s'il n'y a pas d'énergie a dépenser la dessus je ne vous en voudrais pas, comme on dit "qui ne tente rien, n'a rien". Dans tout les cas merci pour votre travail sur vstream globalement.
