### ISSUE TITLE
probleme uptobox hoster

### ISSUE THREAD

**Issue by eldon33** [Kodi-vStream/venom-xbmc-addons#3344]
**Décrivez le bug**

j arrive pas a faire fonctionner les liens uptobox (version beta) quel que soit le site avec un compte gratuit je reçois toujours l' erreur fichier introuvable

**Votre system**

 - OS: [android box ]
- Version Kodi  [19.1]
- Version Vstream 1.3.1

**Nous devons le reproduire**
Pour cela il nous faut:
- Le nom du site : serie streaming/ddl1 etc ...
- Le nom du host (uptobox/uptostream)

**Log**
```
2021-08-04 18:36:11.751 T:18406   DEBUG <general>: CPythonInvoker(39, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): the source file to load is "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py"
2021-08-04 18:36:11.752 T:18406   DEBUG <general>: CPythonInvoker(39, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): setting the Python path to /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.certifi/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.chardet/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.idna/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/site-packages/setuptools-18.4-py3.8.egg:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python38.zip:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/site-packages:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/lib-dynload
2021-08-04 18:36:11.753 T:18406   DEBUG <general>: CPythonInvoker(39, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): entering source directory /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream
2021-08-04 18:36:11.754 T:18406   DEBUG <general>: CPythonInvoker(39, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): instantiating addon using automatically obtained id of "plugin.video.vstream" dependent on version 0.0.0 of the xbmc.python api
2021-08-04 18:36:12.535 T:18406   DEBUG <CAddonSettings[plugin.video.vstream]>: trying to load setting definitions from old format...
2021-08-04 18:36:12.560 T:18406   DEBUG <CSettingsManager>: requested setting (home_update) was not found.
2021-08-04 18:36:12.561 T:18406   DEBUG <CSettingsManager>: requested setting (pastebin_cacheDuration) was not found.
2021-08-04 18:36:12.561 T:18406   DEBUG <CSettingsManager>: requested setting (pastebin_nbItemParPage) was not found.
2021-08-04 18:36:12.564 T:18406    INFO <general>: 	[PLUGIN] vStream: DB engine for db : sqlite3.dbapi2
2021-08-04 18:36:13.712 T:18406    INFO <general>: 	[PLUGIN] vStream: load site serie_streaming and call function showHosters
2021-08-04 18:36:16.651 T:18406    INFO <general>: 	[PLUGIN] vStream: SQLITE 3 as DB engine for tmdb
2021-08-04 18:36:16.695 T:18406   ERROR <general>: NEWADDON Unknown Video Info Key "backdrop_url"
2021-08-04 18:36:16.740 T:18402   DEBUG <general>: Thread waiting -1960838880 terminating
2021-08-04 18:36:16.763 T:18430   DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
2021-08-04 18:36:16.765 T:18430   DEBUG <general>: Saving fileitems [plugin://plugin.video.vstream/?function=showHosters&nextSaisonFunc=showEpisodes&referer=https%3a%2f%2fww1.serie-streaming.io%2famerican-horror-stories-saison-1-episode-1-47848-series-streaming&sCat=8&sEpisode=01&sFav=showHosters&sHost=Uptobox&sLang=VOSTFR&sMovieTitle=American%20Horror%20Stories%20Saison%201%20episode%201&sSeason=01&sThumb=https%3a%2f%2fa.serie-streaming.io%2fposters%2ftv%2f2021-08%2famerican-horror-stories-31892.jpg&saisonUrl=https%3a%2f%2fww1.serie-streaming.io%2famerican-horror-stories-saison-1-3843-seriestreamings&site=serie_streaming&siteUrl=https%3a%2f%2fserie-streaming.io%2fiframeCode%3dZEdscFlXRnRObGhzUmxVeldrUk1Sa0ZMTG14MlNISWpRMUFzTFdoUk1tZ3NkWFZqY1hFd1YzRnhaRVF3UVhSdldsSnJkVkYzUFQwPQ%3d%3d%2f305927&title=American%20Horror%20Stories%20Saison%201%20episode%201%20(VOSTFR)%20%5bCOLOR%20coral%5dUptobox%5b%2fCOLOR%5d]
2021-08-04 18:36:16.768 T:18430   DEBUG <general>:   -- items: 1, sort method: 0, ascending: false
2021-08-04 18:36:16.770 T:18406    INFO <general>: CPythonInvoker(39, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): script successfully run
2021-08-04 18:36:16.770 T:18406   DEBUG <general>: onExecutionDone(39, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py)
2021-08-04 18:36:16.793 T:19147   DEBUG <general>: Thread BackgroundLoader start, auto delete: false
2021-08-04 18:36:16.817 T:19147   DEBUG <general>: Thread BackgroundLoader -1813169888 terminating
2021-08-04 18:36:16.960 T:18406   DEBUG <general>: .
2021-08-04 18:36:17.369 T:18423 WARNING <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 3
2021-08-04 18:36:17.415 T:18430   DEBUG <general>: Keyboard: scancode: 0x14, sym: 0x274, unicode: 0x0000, modifier: 0x0
2021-08-04 18:36:17.415 T:18430   DEBUG <general>: HandleKey: down (0xf081) pressed, action is Down
2021-08-04 18:36:17.453 T:18406    INFO <general>: Python interpreter stopped
2021-08-04 18:36:17.453 T:18406   DEBUG <general>: Thread LanguageInvoker -1869088480 terminating
2021-08-04 18:36:17.579 T:18423 WARNING <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 3
2021-08-04 18:36:17.589 T:18430   DEBUG <general>: Keyboard: scancode: 0x14, sym: 0x274, unicode: 0x0000, modifier: 0x0
2021-08-04 18:36:17.773 T:18423 WARNING <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 3
2021-08-04 18:36:17.788 T:18430   DEBUG <general>: Keyboard: scancode: 0x17, sym: 0x13, unicode: 0x0000, modifier: 0x0
2021-08-04 18:36:17.876 T:18423 WARNING <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 3
2021-08-04 18:36:17.901 T:18430   DEBUG <general>: Keyboard: scancode: 0x17, sym: 0x13, unicode: 0x0000, modifier: 0x0
2021-08-04 18:36:17.901 T:18430   DEBUG <general>: HandleKey: return (0xf00d) pressed, action is Select
2021-08-04 18:36:17.922 T:18430   DEBUG <general>: OnPlayMedia plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=American+Horror+Stories+Saison+1+episode+1+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&sMediaUrl=https%3A%2F%2Fuptobox.com%2Fv17d862xkoce&sHosterIdentifier=uptobox&sFileName=American+Horror+Stories+Saison+1+episode+1&sTitleWatched=americanhorrorstories_S01E01&sTitle=American+Horror+Stories+Saison+1+episode+1+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&sLang=VOSTFR&sId=cHosterGui&siteUrl=https%3A%2F%2Fserie-streaming.io%2FiframeCode%3DZEdscFlXRnRObGhzUmxVeldrUk1Sa0ZMTG14MlNISWpRMUFzTFdoUk1tZ3NkWFZqY1hFd1YzRnhaRVF3UVhSdldsSnJkVkYzUFQwPQ%3D%3D%2F305927&sourceName=serie_streaming&sourceFav=showHosters&nextSaisonFunc=showEpisodes&saisonUrl=https%3A%2F%2Fww1.serie-streaming.io%2Famerican-horror-stories-saison-1-3843-seriestreamings&sCat=8&sCleanTitle=American+Horror+Stories+Saison+1+episode+1+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&sFav=play&sSeason=01&sEpisode=01
2021-08-04 18:36:17.938 T:18430   DEBUG <general>: StartScript - calling plugin vStream('plugin://plugin.video.vstream/','30','?site=cHosterGui&function=play&title=American+Horror+Stories+Saison+1+episode+1+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&sMediaUrl=https%3A%2F%2Fuptobox.com%2Fv17d862xkoce&sHosterIdentifier=uptobox&sFileName=American+Horror+Stories+Saison+1+episode+1&sTitleWatched=americanhorrorstories_S01E01&sTitle=American+Horror+Stories+Saison+1+episode+1+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&sLang=VOSTFR&sId=cHosterGui&siteUrl=https%3A%2F%2Fserie-streaming.io%2FiframeCode%3DZEdscFlXRnRObGhzUmxVeldrUk1Sa0ZMTG14MlNISWpRMUFzTFdoUk1tZ3NkWFZqY1hFd1YzRnhaRVF3UVhSdldsSnJkVkYzUFQwPQ%3D%3D%2F305927&sourceName=serie_streaming&sourceFav=showHosters&nextSaisonFunc=showEpisodes&saisonUrl=https%3A%2F%2Fww1.serie-streaming.io%2Famerican-horror-stories-saison-1-3843-seriestreamings&sCat=8&sCleanTitle=American+Horror+Stories+Saison+1+episode+1+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&sFav=play&sSeason=01&sEpisode=01','resume:false')
2021-08-04 18:36:17.938 T:19316   DEBUG <general>: Thread LanguageInvoker start, auto delete: false
2021-08-04 18:36:17.938 T:19316    INFO <general>: initializing python engine.
2021-08-04 18:36:17.940 T:19316   DEBUG <general>: CPythonInvoker(40, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): start processing
2021-08-04 18:36:17.959 T:19320   DEBUG <general>: Thread scriptobs start, auto delete: false
2021-08-04 18:36:18.067 T:19316   DEBUG <general>: -->Python Interpreter Initialized<--
2021-08-04 18:36:18.067 T:19316   DEBUG <general>: 
                                                   
2021-08-04 18:36:18.067 T:19316   DEBUG <general>: CPythonInvoker(40, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): the source file to load is "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py"
2021-08-04 18:36:18.068 T:19316   DEBUG <general>: CPythonInvoker(40, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): setting the Python path to /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.certifi/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.chardet/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.idna/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/site-packages/setuptools-18.4-py3.8.egg:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python38.zip:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/site-packages:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/lib-dynload
2021-08-04 18:36:18.069 T:19316   DEBUG <general>: CPythonInvoker(40, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): entering source directory /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream
2021-08-04 18:36:18.069 T:19316   DEBUG <general>: CPythonInvoker(40, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): instantiating addon using automatically obtained id of "plugin.video.vstream" dependent on version 0.0.0 of the xbmc.python api
2021-08-04 18:36:18.160 T:18430   DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
2021-08-04 18:36:18.857 T:19316   DEBUG <CAddonSettings[plugin.video.vstream]>: trying to load setting definitions from old format...
2021-08-04 18:36:18.879 T:19316   DEBUG <CSettingsManager>: requested setting (home_update) was not found.
2021-08-04 18:36:18.880 T:19316   DEBUG <CSettingsManager>: requested setting (pastebin_cacheDuration) was not found.
2021-08-04 18:36:18.880 T:19316   DEBUG <CSettingsManager>: requested setting (pastebin_nbItemParPage) was not found.
2021-08-04 18:36:18.883 T:19316    INFO <general>: 	[PLUGIN] vStream: DB engine for db : sqlite3.dbapi2
2021-08-04 18:36:19.939 T:19316    INFO <general>: 	[PLUGIN] vStream: load site cHosterGui and call function play
2021-08-04 18:36:19.945 T:19316    INFO <general>: 	[PLUGIN] vStream: Hoster - play : https://uptobox.com/ ... /v17d862xkoce
2021-08-04 18:36:20.412 T:19316    INFO <general>: 	[PLUGIN] vStream: SQLITE 3 as DB engine for tmdb
2021-08-04 18:36:20.417 T:19316    INFO <general>: 	[PLUGIN] vStream: Utilise compte premium pour hoster uptobox
2021-08-04 18:36:20.428 T:18430   DEBUG <general>: ------ Window Init (DialogSelect.xml) ------
2021-08-04 18:36:20.437 T:18430   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-08-04 18:36:21.853 T:18423 WARNING <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 3
2021-08-04 18:36:21.871 T:18430   DEBUG <general>: Keyboard: scancode: 0x14, sym: 0x274, unicode: 0x0000, modifier: 0x0
2021-08-04 18:36:21.872 T:18430   DEBUG <general>: HandleKey: down (0xf081) pressed, action is Down
2021-08-04 18:36:22.064 T:18423 WARNING <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 3
2021-08-04 18:36:22.073 T:18430   DEBUG <general>: Keyboard: scancode: 0x14, sym: 0x274, unicode: 0x0000, modifier: 0x0
2021-08-04 18:36:22.193 T:18423 WARNING <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 3
2021-08-04 18:36:22.217 T:18430   DEBUG <general>: Keyboard: scancode: 0x17, sym: 0x13, unicode: 0x0000, modifier: 0x0
2021-08-04 18:36:22.281 T:18423 WARNING <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 3
2021-08-04 18:36:22.289 T:18430   DEBUG <general>: Keyboard: scancode: 0x17, sym: 0x13, unicode: 0x0000, modifier: 0x0
2021-08-04 18:36:22.289 T:18430   DEBUG <general>: HandleKey: return (0xf00d) pressed, action is Select
2021-08-04 18:36:22.543 T:18430   DEBUG <general>: ------ Window Deinit (DialogSelect.xml) ------
2021-08-04 18:36:22.662 T:18430   DEBUG <general>: ------ Window Deinit (DialogNotification.xml) ------
2021-08-04 18:36:23.449 T:19316    INFO <general>: 	[PLUGIN] vStream: Auhentification reussie
2021-08-04 18:36:23.452 T:18430   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-08-04 18:36:24.249 T:19316    INFO <general>: 	[PLUGIN] vStream: no premium
2021-08-04 18:36:24.253 T:19316    INFO <general>: 	[PLUGIN] vStream: Utilise compte premium pour hoster uptobox
2021-08-04 18:36:25.054 T:19316    INFO <general>: 	[PLUGIN] vStream: Auhentification reussie
2021-08-04 18:36:26.480 T:19316    INFO <general>: 	[PLUGIN] vStream: Erreur: Fichier introuvable
2021-08-04 18:36:26.487 T:19316   ERROR <general>: Traceback (most recent call last):
                                                   
2021-08-04 18:36:26.487 T:19316   ERROR <general>: 
2021-08-04 18:36:26.488 T:19316   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/gui/hoster.py", line 507, in play
                                                       aLink = oHoster.getMediaLink()
                                                   
2021-08-04 18:36:26.488 T:19316   ERROR <general>: 
2021-08-04 18:36:26.488 T:19316   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/hosters/uptobox.py", line 98, in getMediaLink
                                                       return self.__getMediaLinkByPremiumUser()
                                                   
2021-08-04 18:36:26.488 T:19316   ERROR <general>: 
2021-08-04 18:36:26.488 T:19316   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/hosters/uptobox.py", line 126, in __getMediaLinkByPremiumUser
                                                       return self.__getMediaLinkForGuest()
                                                   
2021-08-04 18:36:26.488 T:19316   ERROR <general>: 
2021-08-04 18:36:26.488 T:19316   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/hosters/uptobox.py", line 114, in __getMediaLinkForGuest
                                                       return oHoster.getMediaLink()
                                                   
2021-08-04 18:36:26.488 T:19316   ERROR <general>: 
2021-08-04 18:36:26.488 T:19316   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/hosters/uptostream.py", line 113, in getMediaLink
                                                       aResult = oParser.parse(r["streamLinks"], sPattern)
                                                   
2021-08-04 18:36:26.488 T:19316   ERROR <general>: 
2021-08-04 18:36:26.488 T:19316   ERROR <general>: TypeError: string indices must be integers
                                                   
2021-08-04 18:36:26.488 T:19316   ERROR <general>: 
2021-08-04 18:36:26.500 T:19316    INFO <general>: CPythonInvoker(40, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): script successfully run
2021-08-04 18:36:26.501 T:19316   DEBUG <general>: onExecutionDone(40, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py)
2021-08-04 18:36:26.757 T:19316   DEBUG <general>: .
2021-08-04 18:36:27.382 T:19316    INFO <general>: Python interpreter stopped
2021-08-04 18:36:27.382 T:19316   DEBUG <general>: Thread LanguageInvoker -1869088480 terminating
2021-08-04 18:36:27.385 T:19320   DEBUG <general>: Thread scriptobs -1960838880 terminating
2021-08-04 18:36:27.397 T:18430   DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
2021-08-04 18:36:27.399 T:18430   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=American+Horror+Stories+Saison+1+episode+1+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&sMediaUrl=https%3A%2F%2Fuptobox.com%2Fv17d862xkoce&sHosterIdentifier=uptobox&sFileName=American+Horror+Stories+Saison+1+episode+1&sTitleWatched=americanhorrorstories_S01E01&sTitle=American+Horror+Stories+Saison+1+episode+1+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&sLang=VOSTFR&sId=cHosterGui&siteUrl=https%3A%2F%2Fserie-streaming.io%2FiframeCode%3DZEdscFlXRnRObGhzUmxVeldrUk1Sa0ZMTG14MlNISWpRMUFzTFdoUk1tZ3NkWFZqY1hFd1YzRnhaRVF3UVhSdldsSnJkVkYzUFQwPQ%3D%3D%2F305927&sourceName=serie_streaming&sourceFav=showHosters&nextSaisonFunc=showEpisodes&saisonUrl=https%3A%2F%2Fww1.serie-streaming.io%2Famerican-horror-stories-saison-1-3843-seriestreamings&sCat=8&sCleanTitle=American+Horror+Stories+Saison+1+episode+1+%5BCOLOR+violet%5DUptobox%5B%2FCOLOR%5D&sFav=play&sSeason=01&sEpisode=01]
2021-08-04 18:36:27.399 T:18430   DEBUG <general>: Playlist Player: one or more items failed to play... aborting playback
2021-08-04 18:36:27.399 T:18430   DEBUG <general>: ------ Window Init (DialogConfirm.xml) ------
2021-08-04 18:36:28.847 T:18430   DEBUG <general>: ------ Window Deinit (DialogNotification.xml) ------

```

**Comment by Arias800** [comment]
Régler avec l'instauration du QRCode sur la version 1.5.0 (puisqu'il est obligatoire de faire un détour par leurs sites pour autoriser l'accès au lien).

**Comment by TmpName** [comment]
Suite ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3377
