### ISSUE TITLE
lancement des films depuis la sections Films

### ISSUE THREAD

**Issue by eldon33** [Kodi-vStream/venom-xbmc-addons#3350]
**Décrivez le bug**
salut
j ai l habitude d ajouter mes films préférés depuis Vstream a la bibliothèque pour les regarder ensuite directement depuis la section  films de kodi . le probleme c que apres la mise a jour 1.4.0 aucun de ces films ne se lance et je reçoit l erreur fichier introuvable ou bien liste de lecture aucun élément suivant a lire.

**Votre system**
 - OS: [Android]
 - Version Kodi  [19.1]
- Version Vstream 1.4.0
- 
![235029088_966350290809431_6813646665672791312_n](https://user-images.githubusercontent.com/87877955/129818737-18006025-8617-451b-a252-1cbf2cc6c59a.jpg)

![235174236_268667771437195_4638072319869813839_n](https://user-images.githubusercontent.com/87877955/129818750-a10c085d-448e-4630-9bfa-f41b67d60998.jpg)

**Comment by TmpName** [comment]
Il faudrait quelques logs, mais si c'est des liens internet, ils sont peut etre morts ?

**Comment by eldon33** [comment]
j ai bien fait la vérification et les liens sont toujours fonctionnels . est ce que le problème peut être du au changement du chemin de la librairie par default ?
voila le log si ca peut aider

```
2021-08-18 16:57:28.577 T:11273 WARNING <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 3
2021-08-18 16:57:28.788 T:11481    INFO <general>: Skipped 1 duplicate messages..
2021-08-18 16:57:28.788 T:11481    INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-08-18 16:57:28.789 T:11481    INFO <general>: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2021-08-18 16:57:28.794 T:11481    INFO <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 63792 m_frames: 1993 m_frameSize: 8 channels: 2
2021-08-18 16:57:30.009 T:11273 WARNING <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 3
2021-08-18 16:57:32.973 T:11278   ERROR <general>: Skipped 3 duplicate messages..
2021-08-18 16:57:32.973 T:11278   ERROR <general>: GetDirectory - Error getting /storage/emulated/0/films/mortal kombat 2021/mortal kombat 2021.strm
2021-08-18 16:57:33.000 T:5791     INFO <general>: initializing python engine.
2021-08-18 16:57:33.822 T:5791     INFO <general>: 	[PLUGIN] vStream: DB engine for db : sqlite3.dbapi2
2021-08-18 16:57:34.661 T:5791     INFO <general>: 	[PLUGIN] vStream: load site cHosterGui and call function play
2021-08-18 16:57:34.666 T:5791     INFO <general>: 	[PLUGIN] vStream: Hoster - play : https://vudeo.net/ ... /embed-qf2lnadq6cn9.html
2021-08-18 16:57:35.477 T:5791     INFO <general>: 	[PLUGIN] vStream: playertype from config: auto
2021-08-18 16:57:35.478 T:5791     INFO <general>: 	[PLUGIN] vStream: player initialized
2021-08-18 16:57:35.478 T:5791     INFO <general>: 	[PLUGIN] vStream: Erreur: Fichier introuvable
2021-08-18 16:57:35.490 T:5791    ERROR <general>: Traceback (most recent call last):
                                                   
2021-08-18 16:57:35.490 T:5791    ERROR <general>: 
2021-08-18 16:57:35.491 T:5791    ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/gui/hoster.py", line 541, in play
                                                       return oPlayer.run(oGuiElement, oHoster.getFileName(), aLink[1])
                                                   
2021-08-18 16:57:35.491 T:5791    ERROR <general>: 
2021-08-18 16:57:35.491 T:5791    ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/player.py", line 95, in run
                                                       item = oGui.createListItem(oGuiElement)
                                                   
2021-08-18 16:57:35.491 T:5791    ERROR <general>: 
2021-08-18 16:57:35.491 T:5791    ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/gui/gui.py", line 342, in createListItem
                                                       data = {key:val for key, val in oGuiElement.getItemValues().items() if val != ""}
                                                   
2021-08-18 16:57:35.491 T:5791    ERROR <general>: 
2021-08-18 16:57:35.491 T:5791    ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/gui/guiElement.py", line 686, in getItemValues
                                                       if sCat and int(sCat) in(1, 2, 3, 4, 5, 8):  # Vérifier seulement si de type média
                                                   
2021-08-18 16:57:35.491 T:5791    ERROR <general>: 
2021-08-18 16:57:35.491 T:5791    ERROR <general>: ValueError: invalid literal for int() with base 10: 'False'
                                                   
2021-08-18 16:57:35.491 T:5791    ERROR <general>: 
2021-08-18 16:57:35.492 T:5791     INFO <general>: CPythonInvoker(18, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): script successfully run
2021-08-18 16:57:36.152 T:5791     INFO <general>: Python interpreter stopped
2021-08-18 16:57:36.188 T:11278   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?function=play&site=cHosterGui&sFileName=Mortal+Kombat+%282021%29&sMediaUrl=https%3A%2F%2Fvudeo.net%2Fembed-qf2lnadq6cn9.html&sHosterIdentifier=vudeo]
```

**Comment by sizanic** [comment]
C'est la même erreur qu'ici : #3348 

Il me faudrait le fichier vStream.db

**Comment by eldon33** [comment]
j ai réinstallé la version Vstream 1.3.1 et les films se se lançaient de nouveau 
~~~
2021-08-18 23:55:45.448 T:16451   ERROR <general>: GetDirectory - Error getting /storage/emulated/0/series/naruto shippuden film 6/naruto shippuden film 6.strm
2021-08-18 23:55:45.476 T:16451   DEBUG <general>: StartScript - calling plugin vStream('plugin://plugin.video.vstream/','117','?function=play&site=cHosterGui&sFileName=Naruto+Shippuden+Film+6+%3A+Road+to+Ninja&sMediaUrl=https%3A%2F%2Fuqload.com%2Fembed-k88khz7olyme.html&sHosterIdentifier=uqload','resume:false')
2021-08-18 23:55:45.477 T:29134   DEBUG <general>: Thread LanguageInvoker start, auto delete: false
2021-08-18 23:55:45.477 T:29134    INFO <general>: initializing python engine.
2021-08-18 23:55:45.477 T:29134   DEBUG <general>: CPythonInvoker(152, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): start processing
2021-08-18 23:55:45.497 T:29138   DEBUG <general>: Thread scriptobs start, auto delete: false
2021-08-18 23:55:45.616 T:29134   DEBUG <general>: -->Python Interpreter Initialized<--
2021-08-18 23:55:45.616 T:29134   DEBUG <general>: 
                                                   
2021-08-18 23:55:45.617 T:29134   DEBUG <general>: CPythonInvoker(152, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): the source file to load is "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py"
2021-08-18 23:55:45.617 T:29134   DEBUG <general>: CPythonInvoker(152, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): setting the Python path to /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.certifi/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.chardet/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.dnspython/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.idna/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/site-packages/setuptools-18.4-py3.8.egg:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python38.zip:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/site-packages:/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/lib-dynload
2021-08-18 23:55:45.618 T:29134   DEBUG <general>: CPythonInvoker(152, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): entering source directory /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream
2021-08-18 23:55:45.618 T:29134   DEBUG <general>: CPythonInvoker(152, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): instantiating addon using automatically obtained id of "plugin.video.vstream" dependent on version 0.0.0 of the xbmc.python api
2021-08-18 23:55:45.698 T:16451   DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
2021-08-18 23:55:46.322 T:29134   DEBUG <CAddonSettings[plugin.video.vstream]>: trying to load setting definitions from old format...
2021-08-18 23:55:46.343 T:29134   DEBUG <CSettingsManager>: requested setting (pastebin_cacheDuration) was not found.
2021-08-18 23:55:46.343 T:29134   DEBUG <CSettingsManager>: requested setting (pastebin_nbItemParPage) was not found.
2021-08-18 23:55:46.346 T:29134    INFO <general>: 	[PLUGIN] vStream: DB engine for db : sqlite3.dbapi2
2021-08-18 23:55:47.319 T:29134    INFO <general>: 	[PLUGIN] vStream: load site cHosterGui and call function play
2021-08-18 23:55:47.324 T:29134    INFO <general>: 	[PLUGIN] vStream: Hoster - play : https://uqload.com/ ... /embed-k88khz7olyme.html
2021-08-18 23:55:47.374 T:16451   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-08-18 23:55:48.122 T:29134    INFO <general>: 	[PLUGIN] vStream: playertype from config: dvdplayer
2021-08-18 23:55:48.122 T:29134    INFO <general>: 	[PLUGIN] vStream: player initialized
2021-08-18 23:55:48.155 T:29134    INFO <general>: 	[PLUGIN] vStream: Player use setResolvedUrl() method
2021-08-18 23:55:48.185 T:16451   DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
2021-08-18 23:55:48.185 T:29138   DEBUG <general>: Thread scriptobs -2084570848 terminating
2021-08-18 23:55:48.210 T:16451   DEBUG <general>: CPlayerCoreFactory::GetPlayers(https://m130.uqload.org/3rfkwa4nbvw2q4drdiq7dlhyko5qckbtqshyyrh2pefn27lu4ipieyvd5ktq/v.mp4|User-Agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36&Referer=https://uqload.com/embed-k88khz7olyme.html)
2021-08-18 23:55:48.210 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: system rules
2021-08-18 23:55:48.210 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: matches rule: system rules
2021-08-18 23:55:48.210 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
2021-08-18 23:55:48.210 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
2021-08-18 23:55:48.210 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
2021-08-18 23:55:48.210 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
2021-08-18 23:55:48.211 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: streams
2021-08-18 23:55:48.211 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: matches rule: streams
2021-08-18 23:55:48.211 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: aacp/sdp
2021-08-18 23:55:48.211 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: mp2
2021-08-18 23:55:48.211 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: dvd
2021-08-18 23:55:48.211 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: discimage
2021-08-18 23:55:48.211 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
2021-08-18 23:55:48.211 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: nsv
2021-08-18 23:55:48.211 T:16451   DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: radio
2021-08-18 23:55:48.211 T:16451   DEBUG <general>: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
2021-08-18 23:55:48.212 T:16451   DEBUG <general>: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
2021-08-18 23:55:48.212 T:16451   DEBUG <general>: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
2021-08-18 23:55:48.212 T:16451   DEBUG <general>: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
2021-08-18 23:55:48.212 T:16451   DEBUG <general>: CPlayerCoreFactory::GetPlayers: added 1 players
2021-08-18 23:55:48.216 T:16451   DEBUG <general>: Radio UECP (RDS) Processor - new CDVDRadioRDSData
2021-08-18 23:55:48.217 T:16451    INFO <general>: VideoPlayer::OpenFile: /storage/emulated/0/series/naruto shippuden film 6/naruto shippuden film 6.strm
2021-08-18 23:55:48.219 T:16451   DEBUG <general>: easy_acquire - Created session to https://m130.uqload.org
2021-08-18 23:55:48.696 T:16451   DEBUG <general>: CCurlFile::GetMimeType - https://m130.uqload.org/3rfkwa4nbvw2q4drdiq7dlhyko5qckbtqshyyrh2pefn27lu4ipieyvd5ktq/v.mp4|User-Agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36&Referer=https://uqload.com/embed-k88khz7olyme.html -> video/mp4
2021-08-18 23:55:48.697 T:29615   DEBUG <general>: Thread VideoPlayer start, auto delete: false
2021-08-18 23:55:48.697 T:16451   DEBUG <general>: OnPlayBackStarted: CApplication::OnPlayBackStarted
2021-08-18 23:55:48.699 T:29615    INFO <general>: Creating InputStream
2021-08-18 23:55:48.704 T:29615   DEBUG <general>: CurlFile::Open(0x83bff250) https://m130.uqload.org/3rfkwa4nbvw2q4drdiq7dlhyko5qckbtqshyyrh2pefn27lu4ipieyvd5ktq/v.mp4
2021-08-18 23:55:48.714 T:28376   DEBUG <general>: Loading settings for /storage/emulated/0/series/naruto shippuden film 6/naruto shippuden film 6.strm
2021-08-18 23:55:48.739 T:16451   DEBUG <general>: CVideoGUIInfo::InitCurrentItem(/storage/emulated/0/series/naruto shippuden film 6/naruto shippuden film 6.strm)
2021-08-18 23:55:48.788 T:16451   DEBUG <general>: CPlayerGUIInfo::InitCurrentItem(/storage/emulated/0/series/naruto shippuden film 6/naruto shippuden film 6.strm)
2021-08-18 23:55:48.790 T:16499   DEBUG <general>: void CXBMCApp::OnPlayBackStarted()
2021-08-18 23:55:48.795 T:16499   DEBUG <general>: Visible Behind request: true
~~~

**Comment by TmpName** [comment]
Y a un soucis ici aussi

`sCat = str(self.getCat())`
Si sCat  = False, il devient "False", et du coup cette ligne ne marche plus 

`if sCat and int(sCat) in(1, 2, 3, 4, 5, 8):`

**Comment by sizanic** [comment]
oui, j'ai vu ce sCat="false".
et je suis d'accord pour enlever le str( ).

Par contre je ne comprend pas le log dans cet autre issue : #3348 
On se retrouve avec un 'search3'.
```
  if sCat and int(sCat) in(1, 2, 3, 4, 5, 8):  # Vérifier seulement si de type média
-> ValueError: invalid literal for int() with base 10: 'search3'
```

Il y aura toujours le probleme de conversion en int.

Du coup faut voir pour un code plutot : 
`if sCat and sCat in('1', '2', '3', '4', '5', '8'):`

(a tester)

**Comment by TmpName** [comment]
Ha oui, ..... sCat serait "search3"

Oui, et au moins on est sur que ca marche a tout les coup, ou alors modifier la fonction self.getCat() pour quelle ne retourne que des int ou false, mais je vois pas d'ou vient le "search3" et si il ne serait pas utile a un autre moment.

**Comment by sizanic** [comment]
J'ai trouvé un seul 'search' ici, en L430 :  

https://github.com/Kodi-vStream/venom-xbmc-addons/commit/066077107339d2d32b40c4290a64d3be858ad08a#diff-96fe30ab7b96581a9b589cb1ee5c02046bb6e35417e3dd9babc96de47ba4ad48

Mais pour un attribut sType, alors que le sCat est traité en dessous.

J'en est quand même profité pour l'enlever car je ne vois pas à quoi il servait 🤔

**Comment by TmpName** [comment]
Lol, meilleure prise que moi ^^
Moi j'ai rien trouvé du tout .... Impossible de trouver d'ou vient ce "search3", un reliquat dans la base de donnée ...

**Comment by Popoffake** [comment]
Bonjour à tous,
j'ai le même problème que celui décrit dans le premier post :
Les films de mon compte uptobox que j'ajoute à ma librairie sont illisibles, alors que je peux les lancer sans problème depuis mon compte dans vstream.

J'ai fouillé un peu partout, sans trouver de solution.

**Comment by alKODIque** [comment]
Hello :)
Je viens de faire un petit test afin de reproduire l'erreur en ajoutnt un film à partir de mon compte uptobox dans la médiathèque de kodi...

J'obtiens le même résulat que Popof..

Voici mon log, on peut voir ce qui se passe à partir de la ligne no.5146
[kodi.log](https://github.com/Kodi-vStream/venom-xbmc-addons/files/7112085/kodi.log)

**Comment by TmpName** [comment]
Ben si je compare un lien qui fonctionne et celui la, il y a quand meme pas mal de differences 

`plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=The+Night+[fullHD]+[COLOR+skyblue]Lien+direct[/COLOR]+[COLOR+khaki][/COLOR]&sCat=1&sMediaUrl=https://www39.uptobox.com/dl/xaektHx6_zfZ5tcVrgWqDfJrgkfviB1YyRyxnpUrP_KoqfNH9nzT7pRcP4U4-UCY34k2UEBwjYA5ESPl5dsBciszSrjM5C8zP69fKkohdV4YegZ-qbMTJuGFP3sLMQoZ7QrGC2Wtb6CUFwJGsMFYHw/The+Night+(2021)+TM746781TM&sHosterIdentifier=lien_direct&sFileName=The+Night&sTitleWatched=thenight&sTitle=The+Night+&sId=cHosterGui&siteUrl=https://pastebin.com/raw/&sMedia=film&pasteID=1&sYear=2021&idTMDB=746781&sTitle=The+Night&sTmdbId=746781&sourceName=pastebin&sourceFav=showHosters&movieUrl=https://pastebin.com/raw/&sMedia=film&pasteID=1&sYear=2021&idTMDB=746781&sTitle=The+Night&movieFunc=showHosters`

et

`plugin://plugin.video.vstream/?function=play&site=cHosterGui&sFileName=Worth+(2021)&sMediaUrl=https://uptobox.com/g9haltq3i89v&sHosterIdentifier=uptobox`

Il y en a un avec l'url décodée, et pas l'autre.

**Comment by alKODIque** [comment]
Oui, mais les liens déja décodés par pastebin sont temporaires.. On ne peut pas les ajouter a la médiathèque, ça ne donne rien.

Par contre, les lien provenant directement de notre compte uptobox (dans vStream), ont toujours bien fonctionnés si ajoutés à la médiathèque jusqu'à récemment..  C'est possible que vous appelez l'API différemment depuis peu?

**Comment by TmpName** [comment]
Essayes en editant le fichier guiElement.py vers la ligne 680


```
        # Used only if there is data in db, overwrite getMetadonne()
        sCat = str(self.getCat())
        if sCat and int(sCat) in(1, 2, 3, 4, 5, 8):  # Vérifier seulement si de type média
            if self.getWatched():
                self.addItemValues('playcount', 1)
```

A corriger par


```
        # Used only if there is data in db, overwrite getMetadonne()
        sCat = str(self.getCat())
        try:
            if sCat and int(sCat) in(1, 2, 3, 4, 5, 8):  # Vérifier seulement si de type média
                if self.getWatched():
                    self.addItemValues('playcount', 1)
        except:
            pass
```

**Comment by alKODIque** [comment]
Merci!! J'essaie ça... efefctivement, les types de média ne sont pas catégorisés dans uptobox ,

**Comment by alKODIque** [comment]
Je peux pas tester si ca fonctionne..
À cause de cet erreur notée ici: https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3364

Même si j'efface mon token dans les paramètres, impossible d'entrer dans mon compte uptobox depuis vStream
(Je viens encore de recevoir le email de uptobox qui me dit que j'essaie d'entrer dans mon compte depuis un pays différent que le mien)

**Comment by Popoffake** [comment]
J'ai tenté sur ma config et ça a fait foirer tout Kodi. Impossible de lancer la moindre extension (et pas que vstream).
C'est à n'y rien comprendre.
J'ai probablement fait une mauvaise manip. Mais j'ai bien essayé 5 fois.
(je tourne sous android tv)

**Comment by alKODIque** [comment]
@Popoffake 
As-tu essayé depuis la beta ou depuis la derniere version stable de vStream lorsque tu as changé le fichier?

**Comment by Popoffake** [comment]
@alKODIque 
J'ai la dernière version stable.

**Comment by donguiza** [comment]
> Essayes en editant le fichier guiElement.py vers la ligne 680
> 
> ```
>         # Used only if there is data in db, overwrite getMetadonne()
>         sCat = str(self.getCat())
>         if sCat and int(sCat) in(1, 2, 3, 4, 5, 8):  # Vérifier seulement si de type média
>             if self.getWatched():
>                 self.addItemValues('playcount', 1)
> ```
> 
> A corriger par
> 
> ```
>         # Used only if there is data in db, overwrite getMetadonne()
>         sCat = str(self.getCat())
>         try:
>             if sCat and int(sCat) in(1, 2, 3, 4, 5, 8):  # Vérifier seulement si de type média
>                 if self.getWatched():
>                     self.addItemValues('playcount', 1)
>         except:
>             sCat = False
> ```
> 
> Ca devrait corriger ton erreur `2021-09-05 13:42:52.983 T:2341 ERROR <general>: ValueError: invalid literal for int() with base 10: 'False'`

merci beaucoup je viens de tester la correction et les films se lançaient de nouveau
