### ISSUE TITLE
Fermeture du lecteur sans erreur sur voiranime

### ISSUE THREAD

**Issue by victorbnl** [Kodi-vStream/venom-xbmc-addons#4019]
**Décrivez le bug**

Quand j'essaye de voir un anime sur voiranime et que je clique sur l'épisode, un chargement s'affiche pendant quelques secondes, puis se ferme pour revenir sur la liste des épisodes, sans produire aucune notification.

**Votre system**
- OS: Windows 11
- Appareil: PC
- Version Kodi: 20.0.0
- Version Vstream: 2.4.3

**Nous devons le reproduire**

- Nom du site: voiranime
- Titre du fim/serie: One piece VOSTFR E001
- Nom du host (openload/vidzi/...): 

**Log**

```
2023-03-11 19:57:04.186 T:12092    info <general>: 	[PLUGIN] vStream: load site voiranime and call function showLinks
2023-03-11 19:57:10.663 T:12092    info <general>: 	[PLUGIN] vStream: could not load site: voiranime error: 'NoneType' object has no attribute 'group'
2023-03-11 19:57:10.664 T:12092   error <general>: Traceback (most recent call last):
                                                   
2023-03-11 19:57:10.664 T:12092   error <general>: 
2023-03-11 19:57:10.664 T:12092   error <general>:   File "C:\Users\Victor\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 166, in parseUrl
                                                       function()
                                                   
2023-03-11 19:57:10.664 T:12092   error <general>: 
2023-03-11 19:57:10.664 T:12092   error <general>:   File "C:\Users\Victor\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites\voiranime.py", line 303, in showLinks
                                                       post = data.group(1)
                                                   
2023-03-11 19:57:10.664 T:12092   error <general>: 
2023-03-11 19:57:10.664 T:12092   error <general>: AttributeError: 'NoneType' object has no attribute 'group'
                                                   
2023-03-11 19:57:10.664 T:12092   error <general>: 
2023-03-11 19:57:10.697 T:5132    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=showLinks&nextSaisonFunc=showEpisodes&sCat=8&sDesc=%5bI%5d%5bCOLOR%20grey%5dSynopsis%20%3a%5b%2fCOLOR%5d%5b%2fI%5d%20True&sFav=showLinks&sMeta=6&sMovieTitle=One%20Piece%20-%200001%20VOSTFR%20-%200001%20&sThumb=https%3a%2f%2fv2.voiranime.com%2fwp-content%2fuploads%2f2020%2f01%2fthumb_5e10959f42183-110x150.jpg&saisonUrl=https%3a%2f%2fv2.voiranime.com%2fanime%2fone-piece%2f&site=voiranime&siteUrl=https%3a%2f%2fv2.voiranime.com%2fanime%2fone-piece%2fone-piece-0001-vostfr%2f&title=One%20Piece%20-%200001%20VOSTFR%20-%200001%20
2023-03-11 19:57:10.712 T:8116    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showLinks&nextSaisonFunc=showEpisodes&sCat=8&sDesc=%5bI%5d%5bCOLOR%20grey%5dSynopsis%20%3a%5b%2fCOLOR%5d%5b%2fI%5d%20True&sFav=showLinks&sMeta=6&sMovieTitle=One%20Piece%20-%200001%20VOSTFR%20-%200001%20&sThumb=https%3a%2f%2fv2.voiranime.com%2fwp-content%2fuploads%2f2020%2f01%2fthumb_5e10959f42183-110x150.jpg&saisonUrl=https%3a%2f%2fv2.voiranime.com%2fanime%2fone-piece%2f&site=voiranime&siteUrl=https%3a%2f%2fv2.voiranime.com%2fanime%2fone-piece%2fone-piece-0001-vostfr%2f&title=One%20Piece%20-%200001%20VOSTFR%20-%200001%20) failed
```

**Plus**

J'ai une instance de FlareSolverr lancée

**Comment by TmpName** [comment]
De mon coté j'arrive pas a me connecter au site via navigateur, tu peux tester de ton coté ?

**Comment by victorbnl** [comment]
Sur le navigateur aucun problème je peux regarder l’épisode en question

**Comment by TmpName** [comment]
Donc chez toi cette url fonctionne ? `https://v2.voiranime.com/`

**Comment by sizanic** [comment]
chez moi cette url fonctionne (après une fenêtre CloudFlare), avec DNS google.

**Comment by TmpName** [comment]
Moi c'est pas le dns qui deconne, mais cloudflare, j'ai un "check de navigateur" qui tourne en boucle.

**Comment by victorbnl** [comment]
Oui chez moi cette url fonctionne

**Comment by victorbnl** [comment]
Et j’ai pas ce problème de Cloudflare, j’ai effectivement une vérification de Cloudflare mais qui tourne pas en boucle, et après je peux naviguer sur le site sans problème

**Comment by TmpName** [comment]
Je dois avoir un addon que leur protection a la con ne doit pas aimer.

**Comment by TmpName** [comment]
Bon ben ca veut pas passer avec firefow, mais ca passe avec Chrome.
Probleme j'utilise firefox avec Falresolver, et pas de version compilé pour windows encore.
Du coup j'ai fais a tatons.

Essayes en editant le fichier [voiranime.py](https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/sites/voiranime.py) ligne 302
`data = re.search('data-action="bookmark" data-post="([^"]+)" data-chapter="([^"]+)"', sHtmlContent)`

a remplacer par

`data = re.search('data-manga="([^"]+)" data-chapter="([^"]+)', sHtmlContent)`

Ca ne devrait pas marcher, car il faut une modif pour que Flaresolver marche pour les requetes POSTs, mais ton erreur devrait etre differente.

**Comment by TmpName** [comment]
Des news (mauvaises) ici https://github.com/Kodi-vStream/venom-xbmc-addons/issues/4057
