### ISSUE TITLE
Marquage vu avec la beta

### ISSUE THREAD

**Issue by razorex** [Kodi-vStream/venom-xbmc-addons#4037]
Perte des marqué vu précédent plus plus de fonctionnement du marquage, le log. je précise que j'ai delete ma db vstream pour tester avant :

EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'sqlite3.OperationalError'>
                                                   Error Contents: table watched has no column named fav
                                                   Traceback (most recent call last):
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\db.py", line 251, in insert_watched
                                                       self.dbcur.execute(ex, (tmdbId, titleWatched, title, siteurl, site, cat, fav, season))
                                                   sqlite3.OperationalError: table watched has no column named fav
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 317, in <module>
                                                       main()
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 48, in __init__
                                                       self.parseUrl()
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 100, in parseUrl
                                                       if isGui(sSiteName, sFunction):
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 225, in isGui
                                                       exec("oGui." + sFunction + "()")
                                                     File "<string>", line 1, in <module>
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\gui\gui.py", line 802, in setWatched
                                                       db.insert_watched(meta)
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\db.py", line 272, in insert_watched
                                                       self.dbcur.execute(ex, (tmdbId, titleWatched, title, siteurl, site, cat, fav, season))
                                                   sqlite3.OperationalError: table watched has no column named fav
                                                   -->End of Python script error report<--

**Comment by sizanic** [comment]
je regarde ça rapidement 👍🏻

**Comment by razorex** [comment]
j'ai fais une correction ajout de la colonne 'fav' dans les watched par contre j'ai du delete la db vstream pour que sa fonctionne.

**Comment by sizanic** [comment]
Il y a une nouvelle fonctionnalité qui a été mise en place autour des medias vus, qui permet de les voir dans un menu.
Je vais regarder pour reprendre les changements afin de voir si on peut conserver la base sans perdre l'historique.

**Comment by razorex** [comment]
c'était trop facile malheureusement, sa marche pour les films ou une saison entiere mais pas quand je marque vu un épisode

maintenant j'ai sa:
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
Error Type: <class 'ValueError'> Error Contents: substring not found Traceback (most recent call last):
File "C:\Users*\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 317, in main()
File "C:\Users*\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 48, in __init__self.parseUrl()
File "C:\Users*\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 100, in parseUrl if isGui(sSiteName, sFunction):
File "C:\Users*\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 225, in isGui exec("oGui." + sFunction + "()")
File "", line 1, in
File "C:\Users\Herve\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\gui\gui.py", line 802, in setWatched db.insert_watched(meta)
File "C:\Users**\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\db.py", line 277, in insert_watched
tvshowtitle = title[:title.rindex('E')].strip()
ValueError: substring not found
-->End of Python script error report<--

**Comment by razorex** [comment]
Oui j'avais vu que les soucis récent était en rapport avec cet ajout de menu, pour moi un de plus mais pour quel  intérêts ???
Un historique de visionnage, le marquage vu ne te suffit pas ??

**Comment by sizanic** [comment]
> le marquage vu ne te suffit pas

Moi si, ça me suffit, mais pas nos utilisateurs, c'est une fonctionnalité qui a été demandée.

Un historique de visionnage est quand même différent d'un petit indicateur que l'on voit de temps en temps lorsqu'on navigue.
Ici on peut vraiment retrouver la liste complète de ses visionnages.

C'est une fonctionnalité de base proposée par toute plateforme de diffusion qui se respecte 😄

**Comment by sizanic** [comment]
Probleme "Marquer vu" corrigé avec la derniere version 2.5.0.
