### ISSUE TITLE
Problème lecture fichier Strm - SetCountries

### ISSUE THREAD

**Issue by peto51** [Kodi-vStream/venom-xbmc-addons#4124]
Bonjour,

Depuis quelques temps, mes fichiers Strm ne peuvent pas être lu, il me met une Erreur "SetCountries", et si je met cette ligne en commentaire dans le fichier Gui.py, ça fonctionne.
Désolé c'est peut être un peu vague. Si besoin je met le log en rentrant du taff.

C'est sur une nvidia shield

Merci beaucoup par avance, je donnerais plus de précision, a moins que vous ayez déjà une idée du problème.

**Comment by peto51** [comment]
Personne n'a pu identifier mon problème ?

**Comment by sizanic** [comment]
Bonjour,

Nous sommes une toute petite équipe et c'est le week-end 😉 
Patience...

**Comment by peto51** [comment]
Oui bien-sûr je comprend tout à fait, c'était pour relancer un coup.

**Comment by peto51** [comment]
je vous met mon log lors de l'erreur

```
2023-11-06 20:21:35.175 T:24135    info <general>: 	[PLUGIN] vStream: load site cHosterGui and call function play
2023-11-06 20:21:35.176 T:24135    info <general>: 	[PLUGIN] vStream: Hoster - play : https://1fichier.com/ ... /?b4tzu9g5fgr5478sxgu8
2023-11-06 20:21:35.600 T:24135    info <general>: 	[PLUGIN] vStream: SQLITE 3 as DB engine for tmdb
2023-11-06 20:21:35.604 T:24135    info <general>: 	[PLUGIN] vStream: Utilise compte premium pour hoster onefichier
2023-11-06 20:21:35.781 T:24135    info <general>: 	[PLUGIN] vStream: Auhentification reussie
2023-11-06 20:21:37.206 T:24135    info <general>: 	[PLUGIN] vStream: https://a-2.1fichier.com/p812960140|Cookie=SID=4GQydBMFCbJzVGLO9HjKfZOqy6eKWyNK0MWzJD2TLFqCX3gmbtTSJSOV8=By1keM;
2023-11-06 20:21:37.231 T:24135    info <general>: 	[PLUGIN] vStream: playertype from config: dvdplayer
2023-11-06 20:21:37.231 T:24135    info <general>: 	[PLUGIN] vStream: player initialized
2023-11-06 20:21:37.283 T:24135   error <general>: EXCEPTION: The parameter "countries" must be either a Tuple or a List.
2023-11-06 20:21:37.284 T:24135    info <general>: 	[PLUGIN] vStream: Erreur: Fichier introuvable
2023-11-06 20:21:37.296 T:24135   error <general>: Traceback (most recent call last):
                                                   
2023-11-06 20:21:37.296 T:24135   error <general>: 
2023-11-06 20:21:37.303 T:24135   error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/gui/hoster.py", line 425, in play
                                                       return oPlayer.run(oGuiElement, aLink[1])
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2023-11-06 20:21:37.303 T:24135   error <general>: 
2023-11-06 20:21:37.303 T:24135   error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/player.py", line 106, in run
                                                       item = oGui._createListItem(oGuiElement)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2023-11-06 20:21:37.303 T:24135   error <general>: 
2023-11-06 20:21:37.303 T:24135   error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/gui/gui.py", line 428, in _createListItem
                                                       videoInfoTag.setCountries(data.get('country', [""]))
                                                   
2023-11-06 20:21:37.303 T:24135   error <general>: 
2023-11-06 20:21:37.304 T:24135   error <general>: TypeError: The parameter "countries" must be either a Tuple or a List.
                                                   
2023-11-06 20:21:37.304 T:24135   error <general>: 
2023-11-06 20:21:37.434 T:23949   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vstream/?site=cHosterGui&function=play&sHosterIdentifier=1fichier&sMediaUrl=https://1fichier.com/?b4tzu9g5fgr5478sxgu8&af=3601079.mkv&sFileName=Le Seigneur des anneaux La Communauté de l'anneau (2001)]
```

**Comment by peto51** [comment]
Aucune idée du pourquoi j'ai cette erreur ?

**Comment by sizanic** [comment]
Le log apporte déjà des informations.

J'ai testé le lien et j'ai réussi à lire la vidéo, en passant par "Ouvrir un lien" et avec un compte alldebrid.

Il s'agit d'un lien 1fichier, utilises-tu un compte 1fichier premium ?

**Comment by peto51** [comment]
Oui le lien est validé j'utilise un compte premium pas de soucis.
Il met un problème de lecture avec l'erreur que j'ai mis dans le log.
Et lorsque dans le fichier gui.py je met la ligne videoInfoTag.setCountries(data.get('country', [""])) en commentaire, ça marche.
Sauf que le fichier gui.py se réinitialise tout seul.
A quoi correspond ce SetCountries, est ce qu'il faut que j'ajoute un paramètre dans mes fichiers Strm ?

**Comment by sizanic** [comment]
Je ne vois pas à quoi ça correspond,
mais il y aura une modification dans la prochaine version de vStream pour mieux supporter cette information 👍🏻

**Comment by sizanic** [comment]
La version 2.7.3 de vStream vient de sortir et devrait corriger ton souci.

**Comment by peto51** [comment]
Merci @sizanic
