### ISSUE TITLE
probleme streamzer net

### ISSUE THREAD

**Issue by dln35** [Kodi-vStream/venom-xbmc-addons#825]
bonjour venom,

tout d'abord merci pour cet excellent addon que j'utilise tous les jours!

depuis quelques jours je n'ai plus acces à streamzer net que j'utilisais tous les jours depuis un moment!

maintenant dans vstream il me met "mise en cache veuillez patienter" puis erreur vstream consulter le journal"

les autres serveurs fonctionnent mais plus streamzer net,est-ce normal?

voici ce qui ressort du log de kodi:

`17:26:37 T:140473935058688  NOTICE: 	[PLUGIN] Vstream: load site streamzer_net and call function showMovies
17:26:37 T:140473935058688   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno -2] Name or service not known>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vstream/default.py", line 180, in <module>
                                                main()
                                              File "/storage/.kodi/addons/plugin.video.vstream/default.py", line 31, in __init__
                                                self.parseUrl()
                                              File "/storage/.kodi/addons/plugin.video.vstream/default.py", line 84, in parseUrl
                                                exec "plugin."+ sFunction +"()"
                                              File "<string>", line 1, in <module>
                                              File "/storage/.kodi/addons/plugin.video.vstream/resources/sites/streamzer_net.py", line 267, in showMovies
                                                sHtmlContent = oRequestHandler.request();
                                              File "/storage/.kodi/addons/plugin.video.vstream/resources/lib/handler/requestHandler.py", line 79, in request
                                                return self.__callRequest()
                                              File "/storage/.kodi/addons/plugin.video.vstream/resources/lib/handler/requestHandler.py", line 112, in __callRequest
                                                oResponse = urllib2.urlopen(oRequest, timeout = self.__timeout)
                                              File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-Generic.x86_64-7.0.3/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-Generic.x86_64-7.0.3/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 431, in open
                                              File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-Generic.x86_64-7.0.3/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 449, in _open
                                              File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-Generic.x86_64-7.0.3/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                              File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-Generic.x86_64-7.0.3/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 1227, in http_open
                                              File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-Generic.x86_64-7.0.3/Python-2.7.11/.install_pkg/usr/lib/python2.7/urllib2.py", line 1197, in do_open
                                            URLError: <urlopen error [Errno -2] Name or service not known>
                                            -->End of Python script error report<--
17:26:37 T:140475308972160   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=showMovies&sFav=showMovies&site=streamzer_net&siteUrl=http%3a%2f%2fwww.streamzer.net%2findex.php%3ffile%3dSeries%26op%3dclasse%26secid%3d%26orderby%3dnews%26p%3d1%23stream&title=%5bCOLOR%20gray%5dStreamzer.net%5b%2fCOLOR%5d
17:26:37 T:140475308972160   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showMovies&sFav=showMovies&site=streamzer_net&siteUrl=http%3a%2f%2fwww.streamzer.net%2findex.php%3ffile%3dSeries%26op%3dclasse%26secid%3d%26orderby%3dnews%26p%3d1%23stream&title=%5bCOLOR%20gray%5dStreamzer.net%5b%2fCOLOR%5d) failed`
cela vient de vstream? d'autre part?

merci de ton aide

**Comment by Kodigoal** [comment]
Vu  page facebook , site stoppé.
